package database

import "errors"

var (
	ErrCallTraceNotFound = errors.New("call trace not found")

	errAccountAndIDRequired        = errors.New("account and account ID are required")
	errAccountIDNegative           = errors.New("account ID must not be negative")
	errAccountNotExisted           = errors.New("account not existed")
	errAPIKeyAndIDRequired         = errors.New("API key and key ID are required")
	errAPIKeyNotFound              = errors.New("apikey not found")
	errCallTraceIDRequired         = errors.New("call trace ID is required")
	errCallTraceNil                = errors.New("call trace is nil")
	errCleanupDaysNegative         = errors.New("cleanup days must not be negative")
	errConfigAndIDRequired         = errors.New("config and config ID are required")
	errConfigIdentityImmutable     = errors.New("config type and name cannot be changed")
	errConfigNameInvalid           = errors.New("config name is required and must not have surrounding whitespace")
	errConfigNotFound              = errors.New("config not found")
	errConfigTypeInvalid           = errors.New("config type is required and must not have surrounding whitespace")
	errConfigValueInvalidJSON      = errors.New("config value must be valid JSON")
	errCredentialAndIDRequired     = errors.New("credential ID and credential are required")
	errDatabaseNotOpen             = errors.New("database is not open")
	errDatabaseURLSchemeRequired   = errors.New("database URL must include a scheme")
	errInvalidCallTraceTableName   = errors.New("invalid call trace table name")
	errInvalidPartitionedTable     = errors.New("invalid partitioned table")
	errInvalidTableName            = errors.New("invalid table name")
	errPagePositive                = errors.New("page must be greater than zero")
	errPageSizePositive            = errors.New("page size must be greater than zero")
	errPostgreSQLDatabaseNil       = errors.New("postgresql database is nil")
	errPostgreSQLDatabaseNotOpen   = errors.New("postgresql database is not open")
	errProxyGroupAndIDRequired     = errors.New("proxy group and ID are required")
	errProxyLogNil                 = errors.New("proxy log is nil")
	errSQLiteDatabaseNil           = errors.New("sqlite database is nil")
	errSQLiteDatabaseNotOpen       = errors.New("sqlite database is not open")
	errSQLiteDatabasePathRequired  = errors.New("sqlite database URL must include a path")
	errStoredCredentialInvalidJSON = errors.New("stored credential is invalid JSON")
	errTimeRangeInvalid            = errors.New("start time must not be after end time")
	errTimeRangeRequired           = errors.New("start time and end time are required")
	errUnsupportedDatabaseScheme   = errors.New("unsupported database scheme")
	errUserAndIDRequired           = errors.New("user and user ID are required")
	errUserNotFound                = errors.New("user not found")
)
