import { expect, test } from '@playwright/test'

test('admin and member workflows, gateway, logs, and responsive navigation', async ({ page, browser }, testInfo) => {
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.message))
  await page.goto('/')
  await expect(page).toHaveURL(/\/(?:#.*)?$/)
  await page.getByLabel('用户名', { exact: true }).fill('e2e-admin')
  await page.getByLabel('密码', { exact: true }).fill('wrong-password')
  await page.getByRole('button', { name: '登录控制台' }).click()
  await expect(page.getByRole('alert')).toContainText('用户名或密码错误')
  await page.screenshot({ path: testInfo.outputPath('login.png'), fullPage: true })
  await page.getByLabel('密码', { exact: true }).fill('e2e-admin-password')
  await page.getByRole('button', { name: '登录控制台' }).click()
  await expect(page.getByRole('heading', { name: '个人总览', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '账号管理', exact: true }).click()
  await page.getByRole('button', { name: '添加账号', exact: true }).click()
  await page.getByRole('button', { name: '添加订阅账号', exact: true }).click()
  let dialog = page.getByRole('dialog')
  const platform = dialog.getByRole('combobox', { name: '订阅平台', exact: true })
  await platform.focus()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('listbox')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(platform).toBeFocused()
  await dialog.getByLabel('名称', { exact: true }).fill('Local Dummy')
  await dialog.getByRole('combobox', { name: '订阅平台', exact: true }).click()
  await page.getByRole('option', { name: 'Dummy', exact: true }).click()
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('cell', { name: 'Local Dummy', exact: true })).toBeVisible()
  await page.getByRole('row', { name: '查看 Local Dummy 详情', exact: true }).click()
  await page.getByLabel('名称', { exact: true }).fill('Local Dummy Updated')
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Local Dummy Updated', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'API Key', exact: true }).click()
  await page.getByRole('button', { name: '签发 Key', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('名称', { exact: true }).fill('Local Test Key')
  await dialog.getByRole('button', { name: '签发 Key', exact: true }).click()
  await expect(dialog.getByRole('heading', { name: '签发 API Key' })).toBeVisible()
  await dialog.getByRole('combobox', { name: '绑定账号', exact: true }).click()
  await page.getByRole('option', { name: 'Local Dummy Updated · dummy', exact: true }).click()
  await expect.poll(() => dialog.locator('input').evaluateAll(elements => elements.filter(e => !(e as HTMLInputElement).validity.valid).map(e => ({ id: e.id, value: (e as HTMLInputElement).value, message: (e as HTMLInputElement).validationMessage })))).toEqual([])
  await dialog.getByRole('button', { name: '签发 Key', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Local Test Key' })).toBeVisible()
  const apiKey = await page.getByRole('dialog').getByLabel('API Key', { exact: true }).inputValue()
  expect(apiKey.length).toBeGreaterThan(20)
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('row', { name: '查看 Local Test Key 详情', exact: true }).press('Enter')
  await expect(page.getByRole('dialog').getByLabel('API Key', { exact: true })).toHaveValue(apiKey)
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  const response = await page.request.post('/v1/chat/completions', { headers: { Authorization: `Bearer ${apiKey}`, 'User-Agent': 'codex-tui/1.0', 'Session-Id': 'e2e-conversation' }, data: { model: 'dummy-model' } })
  expect(response.status()).toBe(200)
  expect((await response.json()).model).toBe('dummy-model')
  await page.getByRole('button', { name: '个人总览', exact: true }).click()
  await page.getByRole('button', { name: '查看 Local Test Key 详情', exact: true }).click()
  await expect(page.getByRole('dialog').getByLabel('API Key', { exact: true })).toHaveValue(apiKey)
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('row', { name: /^查看调用/ }).first().click()
  await page.getByRole('dialog').getByRole('button', { name: /^Response Body/ }).click()
  await expect(page.getByRole('dialog')).toContainText('UniSub dummy response')
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '调用记录', exact: true }).click()
  await expect(page.getByRole('cell', { name: /^\/v1\/chat\/completions / })).toBeVisible()
  await expect(page.getByText('e2e-conversation', { exact: true })).toBeVisible()
  const callSearch = page.getByRole('textbox', { name: '搜索调用记录' })
  await expect(callSearch).toHaveAttribute('placeholder', '精确搜索 IP、模型、Session ID、Request ID 或用户名；none 表示系统网络请求')
  expect((await page.getByRole('button', { name: '查询', exact: true }).boundingBox())?.height).toBe((await callSearch.boundingBox())?.height)
  await callSearch.fill('e2e-conversation')
  await callSearch.press('Enter')
  await expect(page.getByRole('cell', { name: /^\/v1\/chat\/completions / })).toBeVisible()
  await page.getByRole('combobox', { name: '账号', exact: true }).click()
  await page.getByRole('option', { name: 'Local Dummy Updated · dummy', exact: true }).click()
  await page.getByRole('combobox', { name: '状态', exact: true }).click()
  await page.getByRole('option', { name: /^500 ·/ }).click()
  await expect(page.getByText('没有符合条件的调用记录', { exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: '状态', exact: true }).click()
  await page.getByRole('option', { name: /^200 ·/ }).click()
  await expect(page.getByRole('cell', { name: /^\/v1\/chat\/completions / })).toBeVisible()
  const rangeGroup = page.getByRole('group', { name: '统计时间范围' })
  const rangeBefore = await rangeGroup.boundingBox()
  await page.getByRole('button', { name: '自定义', exact: true }).click()
  const rangeAfter = await rangeGroup.boundingBox()
  expect(rangeAfter?.height).toBe(rangeBefore?.height)
  expect(rangeAfter?.y).toBe(rangeBefore?.y)
  await page.getByRole('button', { name: '7 天', exact: true }).click()
  await expect(page.getByRole('columnheader', { name: '详情', exact: true })).toHaveCount(0)
  await page.getByRole('row', { name: /^查看调用/ }).click()
  await page.getByRole('dialog').getByRole('button', { name: /^Response Body/ }).click()
  await expect(page.getByRole('dialog')).toContainText('UniSub dummy response')
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('row', { name: /^查看调用/ }).press('Enter')
  await page.getByRole('dialog').getByRole('button', { name: /^Response Body/ }).click()
  await expect(page.getByRole('dialog')).toContainText('UniSub dummy response')
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '用户管理', exact: true }).click()
  await page.getByRole('button', { name: '添加用户', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('用户名', { exact: true }).fill('e2e-member')
  await dialog.getByLabel('新密码', { exact: true }).fill('member-password-123')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'e2e-member', exact: true })).toBeVisible()
  const memberRow = page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'e2e-member', exact: true }) })
  await memberRow.getByRole('switch').click()
  await expect(memberRow.getByRole('switch')).not.toBeChecked()
  await memberRow.getByRole('switch').click()
  await expect(memberRow.getByRole('switch')).toBeChecked()
  await page.getByRole('button', { name: '代理管理', exact: true }).click()
  await page.getByRole('button', { name: '添加代理组', exact: true }).click()
  await page.getByLabel('代理组名称', { exact: true }).fill('Local Proxy Group')
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('请至少添加一个代理地址')
  await page.getByRole('button', { name: '添加地址', exact: true }).click()
  const proxyURL = 'socks5h://oversea.blackjack-local.com:1080'
  const proxyInput = page.getByRole('textbox', { name: '代理 URL', exact: true })
  await proxyInput.fill('ftp://127.0.0.1:1080')
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('代理地址需要是有效的')
  await proxyInput.fill(proxyURL)
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.getByText('未使用', { exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Local Proxy Group', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '编辑 Local Proxy Group', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '代理 URL', exact: true })).toHaveValue(proxyURL)
  await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '删除 Local Proxy Group', exact: true }).click()
  await expect(page.getByRole('alertdialog')).toBeVisible()
  await page.getByRole('alertdialog').getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('alertdialog')).toHaveCount(0)
  await expect(page.getByRole('cell', { name: 'Local Proxy Group', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '系统总览', exact: true }).click()
  await expect(page.getByRole('heading', { name: '账号用量', exact: true })).toBeVisible()
  await expect(page.getByRole('status')).toHaveCount(0)
  await expect(page.getByRole('cell', { name: 'e2e-admin', exact: true })).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('dashboard-desktop.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: '自定义', exact: true }).click()
  await expect(page.getByRole('button', { name: '查询', exact: true })).toBeDisabled()
  expect((await page.getByRole('button', { name: '查询', exact: true }).boundingBox())?.height).toBe((await page.getByLabel('开始日期', { exact: true }).boundingBox())?.height)
  await page.getByLabel('开始日期', { exact: true }).click()
  await expect(page.getByRole('dialog', { name: '选择日期' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('date-picker.png'), animations: 'disabled' })
  await page.getByRole('dialog', { name: '选择日期' }).locator('button[data-day]').filter({ hasText: /^10$/ }).click()
  await expect(page.getByRole('dialog', { name: '选择日期' })).toHaveCount(0)
  await page.getByLabel('结束日期', { exact: true }).click()
  await page.getByRole('dialog', { name: '选择日期' }).locator('button[data-day]').filter({ hasText: /^20$/ }).click()
  await expect(page.getByRole('dialog', { name: '选择日期' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '查询', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '打开导航', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '导航', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '导航', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '打开导航', exact: true }).click()
  await page.getByRole('button', { name: '个人总览', exact: true }).click()
  await expect(page.getByRole('heading', { name: '个人总览', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog', { name: '导航', exact: true })).toHaveCount(0)
  await expect(page.getByRole('status')).toHaveCount(0)
  await expect(page.getByRole('cell', { name: 'dummy-model', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('dashboard-mobile.png'), fullPage: true, animations: 'disabled' })

  const context = await browser.newContext({ baseURL: 'http://127.0.0.1:28080' })
  const member = await context.newPage()
  member.on('pageerror', error => failures.push(error.message))
  await member.goto('/')
  await member.getByLabel('用户名', { exact: true }).fill('e2e-member')
  await member.getByLabel('密码', { exact: true }).fill('member-password-123')
  await member.getByRole('button', { name: '登录控制台' }).click()
  await expect(member.getByRole('heading', { name: '个人总览', exact: true })).toBeVisible()
  await expect(member.getByRole('button', { name: '用户管理', exact: true })).toHaveCount(0)
  expect((await member.request.get('/api/users')).status()).toBe(403)
  await expect(member.getByRole('navigation', { name: '主导航' }).getByRole('button')).toHaveText(['个人总览', 'API Key', '调用记录', '安全设置'])
  for (const path of ['/api/accounts', '/api/suppliers', '/api/suppliers/kimi', '/api/proxy-groups', '/api/usage/users', '/api/oauth/results/missing']) {
    expect((await member.request.get(path)).status()).toBe(403)
  }
  const memberAccounts = await (await member.request.get('/api/keys/accounts')).json()
  expect(memberAccounts.items.length).toBeGreaterThan(0)
  expect(memberAccounts.items.every((a: Record<string, unknown>) => Object.keys(a).sort().join(',') === 'client_types,enabled,id,name,provider')).toBe(true)
  for (const hash of ['overview', 'accounts', 'suppliers/kimi', 'users', 'proxies']) {
    await member.goto('/#' + hash)
    await expect(member.getByRole('heading', { name: '个人总览', exact: true })).toBeVisible()
  }
  await member.getByRole('button', { name: 'API Key', exact: true }).click()
  await expect(member.getByRole('alert')).toHaveCount(0)
  await member.getByRole('button', { name: '调用记录', exact: true }).click()
  await expect(member.getByText('没有符合条件的调用记录', { exact: true })).toBeVisible()
  await member.getByRole('button', { name: '安全设置', exact: true }).click()
  await member.getByLabel('当前密码', { exact: true }).fill('member-password-123')
  await member.getByLabel('新密码', { exact: true }).fill('member-new-password')
  await member.getByLabel('确认新密码', { exact: true }).fill('member-new-password')
  await member.getByRole('button', { name: '保存新密码', exact: true }).click()
  await expect(member.getByRole('status')).toContainText('密码已更新')
  await member.getByRole('button', { name: '退出登录', exact: true }).click()
  await expect(member).toHaveURL(/\/(?:#.*)?$/)
  await expect(member.getByRole('button', { name: '登录控制台' })).toBeVisible()
  expect((await member.request.get('/api/me')).status()).toBe(401)
  await context.close()
  expect(failures).toEqual([])
})

test('session expiry and logout failure stay on the unified entry', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('用户名', { exact: true }).fill('e2e-admin')
  await page.getByLabel('密码', { exact: true }).fill('e2e-admin-password')
  await page.getByRole('button', { name: '登录控制台' }).click()
  await expect(page.getByRole('heading', { name: '个人总览', exact: true })).toBeVisible()
  await page.route('**/api/logout', route => route.fulfill({ status: 500, json: { error: 'logout failed' } }))
  await page.getByRole('button', { name: '退出登录' }).click()
  await expect(page.getByRole('alert')).toContainText('logout failed')
  await expect(page.getByRole('button', { name: '登录控制台' })).toHaveCount(0)
  await page.unroute('**/api/logout')
  // Expire the server session without reloading the page, then trigger a protected query.
  expect((await page.request.post('/api/logout')).status()).toBe(200)
  await page.getByRole('button', { name: '刷新数据' }).click()
  await expect(page.getByRole('button', { name: '登录控制台' })).toBeVisible()
  expect(new URL(page.url()).pathname).toBe('/')
  await expect(page.getByRole('heading', { name: '个人总览', exact: true })).toHaveCount(0)
})
