import { expect, test } from '@playwright/test'

test('AI provider groups and model catalog can be configured from the dashboard', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByLabel('用户名', { exact: true }).fill('e2e-admin')
  await page.getByLabel('密码', { exact: true }).fill('e2e-admin-password')
  await page.getByRole('button', { name: '登录控制台' }).click()
  await expect(page.getByRole('heading', { name: '个人总览', exact: true })).toBeVisible()
  for (const name of ['Routing A', 'Routing B']) {
    const created = await page.request.post('/api/ai-providers', { data: { name, provider: 'dummy', config: { client_type: 'OpenAI' } } })
    expect(created.status()).toBe(201)
  }
  // API setup does not invalidate the already-mounted browser query cache.
  await page.reload()
  await expect(page.getByRole('heading', { name: '个人总览', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'AI Provider', exact: true }).click()
  await page.getByRole('button', { name: '添加 AI Provider', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('名称', { exact: true }).fill('Routing Group')
  await dialog.getByRole('combobox', { name: '类型', exact: true }).click()
  await page.getByRole('option', { name: '组', exact: true }).click()
  await expect(dialog.getByRole('combobox', { name: '允许的客户端', exact: true })).toContainText('Any')
  await expect(dialog.getByRole('combobox', { name: '允许的客户端', exact: true })).toBeDisabled()
  await dialog.getByRole('checkbox', { name: /^Routing A/ }).check()
  await dialog.getByRole('checkbox', { name: /^Routing B/ }).check()
  await expect(dialog.getByRole('alert')).toHaveCount(0)
  await dialog.getByRole('spinbutton', { name: 'Routing A 权重', exact: true }).fill('5')
  await expect(dialog.getByRole('combobox', { name: '代理组', exact: true })).toHaveCount(0)
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('provider-group.png'), fullPage: true, animations: 'disabled' })
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('cell', { name: 'Routing Group', exact: true })).toBeVisible()
  const savedProviders = await (await page.request.get('/api/ai-providers')).json()
  expect(savedProviders.items.find((p: { name: string }) => p.name === 'Routing Group').config.client_type).toBe('Any')
  await page.getByRole('button', { name: '编辑 Routing Group', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: 'Routing A 权重', exact: true })).toHaveValue('5')
  await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click()

  await page.getByRole('button', { name: '添加 AI Provider', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('名称', { exact: true }).fill('Routing Dummy')
  await dialog.getByRole('combobox', { name: '订阅平台', exact: true }).click()
  await page.getByRole('option', { name: 'Dummy', exact: true }).click()
  await dialog.getByRole('checkbox', { name: '仅允许原厂客户端' }).check()
  await expect(dialog.getByRole('combobox', { name: '允许的客户端', exact: true })).toHaveCount(0)
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  let dummyProviders = await (await page.request.get('/api/ai-providers')).json()
  const dummyConfig = dummyProviders.items.find((p: { name: string }) => p.name === 'Routing Dummy').config
  expect(dummyConfig.client_type).toBe('Anthropic')
  expect(dummyConfig.official_only).toBeUndefined()
  await page.getByRole('button', { name: '编辑 Routing Dummy', exact: true }).click()
  await expect(dialog.getByRole('checkbox', { name: '仅允许原厂客户端' })).toBeChecked()
  await dialog.getByRole('checkbox', { name: '仅允许原厂客户端' }).uncheck()
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  dummyProviders = await (await page.request.get('/api/ai-providers')).json()
  expect(dummyProviders.items.find((p: { name: string }) => p.name === 'Routing Dummy').config.client_type).toBe('Any')

  await page.getByRole('button', { name: '添加 AI Provider', exact: true }).click()
  dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: '网页登录授权' })).toBeVisible()
  await dialog.getByRole('checkbox', { name: '仅允许原厂客户端' }).check()
  await expect(dialog.getByRole('combobox', { name: '允许的客户端', exact: true })).toHaveCount(0)
  await expect(dialog.getByLabel('认证方式', { exact: true })).toHaveCount(0)
  await dialog.getByRole('combobox', { name: '类型', exact: true }).click()
  await page.getByRole('option', { name: 'API', exact: true }).click()
  await expect(dialog.getByRole('button', { name: '网页登录授权' })).toHaveCount(0)
  await expect(dialog.getByRole('combobox', { name: '订阅平台' })).toHaveCount(0)
  await expect(dialog.getByRole('combobox', { name: '允许的客户端', exact: true })).toBeEnabled()
  await expect(dialog.getByRole('checkbox', { name: '仅允许原厂客户端' })).toHaveCount(0)
  await dialog.getByLabel('名称', { exact: true }).fill('Routing API')
  await dialog.getByRole('combobox', { name: '模型供应商', exact: true }).click()
  await page.getByRole('option', { name: 'Kimi', exact: true }).click()
  await dialog.getByLabel('上游 API Key', { exact: true }).fill('e2e-not-a-real-key')
  await expect(dialog.getByLabel('Base URL', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('provider-api.png'), fullPage: true, animations: 'disabled' })
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('combobox', { name: '筛选类型', exact: true }).click()
  await page.getByRole('option', { name: 'API', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Routing API', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Routing Group', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '编辑 Routing API', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('combobox', { name: '类型', exact: true })).toBeDisabled()
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('combobox', { name: '筛选类型', exact: true }).click()
  await page.getByRole('option', { name: '全部类型', exact: true }).click()
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('provider-list.png'), fullPage: true, animations: 'disabled' })

  await page.getByRole('link', { name: '模型供应商', exact: true }).click()
  await expect(page).toHaveURL(/#ai-catalog$/)
  await expect(page.getByRole('heading', { name: '模型供应商', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('form', { name: '供应商配置' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: /查看.*详情/ })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('supplier-list.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('row', { name: '查看 Anthropic 详情', exact: true }).click()
  await expect(page).toHaveURL(/#ai-catalog\/anthropic$/)
  await expect(page.getByRole('dialog', { name: 'Anthropic 配置', exact: true })).toBeVisible()
  dialog = page.getByRole('form', { name: '供应商配置' })
  await expect(dialog.getByLabel('Anthropic Claude URL', { exact: true })).toBeVisible()
  await expect(dialog.getByText('当前客户端的原厂模型直接透传，无需默认映射。', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: '添加映射', exact: true }).click()
  await dialog.getByLabel('请求模型', { exact: true }).fill('client-alias')
  await dialog.getByLabel('目标模型', { exact: true }).fill('upstream-model')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('供应商配置已保存')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page).toHaveURL(/#ai-catalog$/)
  await page.getByRole('row', { name: '查看 Kimi 详情', exact: true }).press('Enter')
  await expect(dialog.getByLabel('Kimi Claude URL', { exact: true })).toBeVisible()
  await expect(dialog.getByLabel('haiku 目标模型', { exact: true })).toHaveValue('kimi-k2.5')
  await expect(dialog.getByLabel('请求模型', { exact: true })).toHaveCount(0)
  await expect(dialog.getByLabel('Kimi Claude URL', { exact: true })).toHaveValue('https://api.moonshot.cn/anthropic/v1')
  await expect(dialog.getByLabel('Kimi Claude URL', { exact: true })).toHaveAttribute('readonly', '')
  await expect(dialog.getByRole('button', { name: '恢复默认 URL' })).toHaveCount(0)
  await dialog.getByRole('group', { name: '选择映射客户端' }).getByRole('button', { name: 'Codex', exact: true }).click()
  await expect(dialog.getByLabel('Kimi Codex / Grok URL', { exact: true })).toHaveValue('https://api.moonshot.cn/v1')
  await expect(dialog.getByLabel('Kimi Codex / Grok URL', { exact: true })).toHaveAttribute('readonly', '')
  await dialog.getByLabel('gpt-5.6-luna 目标模型', { exact: true }).fill('kimi-custom-model')
  await dialog.getByRole('group', { name: '选择映射客户端' }).getByRole('button', { name: 'Grok', exact: true }).click()
  await expect(dialog.getByLabel('Kimi Codex / Grok URL', { exact: true })).toHaveValue('https://api.moonshot.cn/v1')
  await expect(dialog.getByLabel('grok-build 目标模型', { exact: true })).toHaveValue('kimi-k2.5')
  const saveButton = dialog.getByRole('button', { name: '保存', exact: true })
  for (const viewport of [{ width: 1440, height: 720 }, { width: 390, height: 667 }]) {
    await page.setViewportSize(viewport)
    const editor = page.getByRole('region', { name: '模型映射列表', exact: true })
    await expect.poll(async () => {
      const box = await saveButton.boundingBox()
      return !!box && box.y >= 0 && box.y + box.height <= viewport.height
    }).toBe(true)
    const before = await saveButton.boundingBox()
    expect(before).not.toBeNull()
    expect(before!.y).toBeGreaterThanOrEqual(0)
    expect(before!.y + before!.height).toBeLessThanOrEqual(viewport.height)
    if (viewport.width < 640) expect(await editor.evaluate(el => el.scrollHeight > el.clientHeight)).toBe(true)
    const fixedControls = [dialog.getByLabel('Kimi Codex / Grok URL', { exact: true }), dialog.getByRole('group', { name: '选择映射客户端' }), dialog.getByRole('button', { name: '添加映射', exact: true })]
    const fixedPositions = await Promise.all(fixedControls.map(control => control.boundingBox()))
    await editor.evaluate(el => { el.scrollTop = el.scrollHeight })
    for (const [index, control] of fixedControls.entries()) expect((await control.boundingBox())?.y).toBe(fixedPositions[index]?.y)
    const after = await saveButton.boundingBox()
    expect(after!.y).toBe(before!.y)
  }
  await page.setViewportSize({ width: 1440, height: 720 })
  await page.getByRole('region', { name: '模型映射列表', exact: true }).evaluate(el => { el.scrollTop = 0 })
  await page.screenshot({ path: testInfo.outputPath('supplier-detail.png'), fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('供应商配置已保存')
  const value = await (await page.request.get('/api/ai-catalog')).json()
  expect(value.catalog.suppliers).toHaveLength(6)
  expect(value.catalog.suppliers.find((s: { id: string }) => s.id === 'anthropic').mappings).toContainEqual({ client: 'Anthropic', model: 'client-alias', target: 'upstream-model' })
  expect(value.catalog.mappings).toBeUndefined()
  const kimi = value.catalog.suppliers.find((s: { id: string }) => s.id === 'kimi')
  expect(kimi.url).toBeUndefined()
  expect(kimi.claude_url).toBe('https://api.moonshot.cn/anthropic/v1')
  expect(kimi.codex_url).toBe('https://api.moonshot.cn/v1')
  expect(kimi.mappings).toEqual([{ client: 'OpenAI', model: 'gpt-5.6-luna', target: 'kimi-custom-model' }])
  await page.reload()
  await expect(page.getByRole('dialog', { name: 'Kimi 配置', exact: true })).toBeVisible()
  await expect(page).toHaveURL(/#ai-catalog\/kimi$/)
  await dialog.getByRole('group', { name: '选择映射客户端' }).getByRole('button', { name: 'Codex', exact: true }).click()
  await expect(dialog.getByLabel('gpt-5.6-luna 目标模型', { exact: true })).toHaveValue('kimi-custom-model')
  await dialog.getByLabel('gpt-5.6-luna 目标模型', { exact: true }).locator('..').getByRole('button', { name: '恢复默认', exact: true }).click()
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('供应商配置已保存')
  const restored = await (await page.request.get('/api/ai-catalog')).json()
  expect(restored.catalog.suppliers.find((s: { id: string }) => s.id === 'kimi').mappings).toEqual([])
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page).toHaveURL(/#ai-catalog$/)
  await expect(page.getByRole('heading', { name: '模型供应商', exact: true })).toBeVisible()
  const providers = await (await page.request.get('/api/ai-providers')).json()
  const group = providers.items.find((p: { name: string }) => p.name === 'Routing Group')
  expect(group.config.client_type).toBe('Any')
  expect(group.config.client_types).toBeUndefined()
})
