import { expect, test } from '@playwright/test'

test('AI provider groups and model catalog can be configured from the dashboard', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByLabel('用户名', { exact: true }).fill('e2e-admin')
  await page.getByLabel('密码', { exact: true }).fill('e2e-admin-password')
  await page.getByRole('button', { name: '登录控制台' }).click()
  await expect(page.getByRole('heading', { name: '个人总览', exact: true })).toBeVisible()
  for (const name of ['Routing A', 'Routing B']) {
    const created = await page.request.post('/api/accounts', { data: { name, config: { kind: 'subscription', supplier: 'dummy', subscription_plan: 'claude_pro', enabled: true, client_type: 'claude' } } })
    expect(created.status()).toBe(201)
  }
  // API setup does not invalidate the already-mounted browser query cache.
  await page.reload()
  await expect(page.getByRole('heading', { name: '个人总览', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '账号管理', exact: true }).click()
  await page.getByRole('button', { name: '添加账号', exact: true }).click()
  await page.getByRole('button', { name: '添加组账号', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('名称', { exact: true }).fill('Routing Group')
  await expect(dialog.getByRole('heading', { name: '添加组账号', exact: true })).toBeVisible()
  await expect(dialog.getByRole('combobox', { name: '类型', exact: true })).toHaveCount(0)
  await expect(dialog.getByLabel('最大并发', { exact: true })).toHaveCount(0)
  await expect(dialog.getByRole('combobox', { name: '允许的客户端', exact: true })).toContainText('不限客户端')
  await expect(dialog.getByRole('table', { name: '组成员', exact: true })).toBeVisible()
  await expect(dialog.getByRole('columnheader')).toHaveText(['选择', '成员', '状态', '权重'])
  await dialog.getByRole('checkbox', { name: /^Routing A/ }).check()
  await dialog.getByRole('checkbox', { name: /^Routing B/ }).check()
  await expect(dialog.getByRole('alert')).toContainText('客户端不一致')
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(dialog).toBeVisible()
  await dialog.getByRole('combobox', { name: '允许的客户端', exact: true }).click()
  await page.getByRole('option', { name: 'Claude', exact: true }).click()
  await expect(dialog.getByRole('alert')).toHaveCount(0)
  await dialog.getByRole('spinbutton', { name: 'Routing A 权重', exact: true }).fill('5')
  await expect(dialog.getByRole('combobox', { name: '代理组', exact: true })).toHaveCount(0)
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('provider-group.png'), fullPage: true, animations: 'disabled' })
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('cell', { name: 'Routing Group', exact: true })).toBeVisible()
  const savedProviders = await (await page.request.get('/api/accounts')).json()
  expect(savedProviders.items.find((p: { name: string }) => p.name === 'Routing Group').config.client_type).toBe('claude')
  await page.getByRole('button', { name: '编辑 Routing Group', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: 'Routing A 权重', exact: true })).toHaveValue('5')
  await expect(dialog.getByRole('combobox', { name: '允许的客户端', exact: true })).toContainText('Claude')
  await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click()

  await page.getByRole('button', { name: '添加账号', exact: true }).click()
  await page.getByRole('button', { name: '添加订阅账号', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('名称', { exact: true }).fill('Routing Dummy')
  await dialog.getByRole('combobox', { name: '订阅平台', exact: true }).click()
  await page.getByRole('option', { name: 'Dummy', exact: true }).click()
  await dialog.getByRole('checkbox', { name: '仅允许原厂客户端' }).check()
  await expect(dialog.getByRole('combobox', { name: '允许的客户端', exact: true })).toHaveCount(0)
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  let dummyProviders = await (await page.request.get('/api/accounts')).json()
  const dummyConfig = dummyProviders.items.find((p: { name: string }) => p.name === 'Routing Dummy').config
  expect(dummyConfig.client_type).toBe('claude')
  expect(dummyConfig.official_only).toBeUndefined()
  await page.getByRole('button', { name: '编辑 Routing Dummy', exact: true }).click()
  await expect(dialog.getByRole('checkbox', { name: '仅允许原厂客户端' })).toBeChecked()
  await dialog.getByRole('checkbox', { name: '仅允许原厂客户端' }).uncheck()
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  dummyProviders = await (await page.request.get('/api/accounts')).json()
  expect(dummyProviders.items.find((p: { name: string }) => p.name === 'Routing Dummy').config.client_type).toBeUndefined()

  await page.getByRole('button', { name: '添加账号', exact: true }).click()
  await page.getByRole('button', { name: '添加订阅账号', exact: true }).click()
  dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: '网页登录授权' })).toBeVisible()
  await dialog.getByRole('checkbox', { name: '仅允许原厂客户端' }).check()
  await expect(dialog.getByRole('combobox', { name: '允许的客户端', exact: true })).toHaveCount(0)
  await expect(dialog.getByLabel('认证方式', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('provider-subscription.png'), fullPage: true, animations: 'disabled' })
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '添加账号', exact: true }).click()
  await page.getByRole('button', { name: '添加API账号', exact: true }).click()
  dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('heading', { name: '添加API账号', exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: '网页登录授权' })).toHaveCount(0)
  await expect(dialog.getByRole('combobox', { name: '订阅平台' })).toHaveCount(0)
  await expect(dialog.getByRole('combobox', { name: '允许的客户端', exact: true })).toBeEnabled()
  await expect(dialog.getByRole('checkbox', { name: '仅允许原厂客户端' })).toHaveCount(0)
  await dialog.getByLabel('名称', { exact: true }).fill('Routing API')
  await dialog.getByRole('combobox', { name: '模型供应商', exact: true }).click()
  await page.getByRole('option', { name: 'Kimi', exact: true }).click()
  await dialog.getByLabel('上游 API Key', { exact: true }).fill('e2e-not-a-real-key')
  await expect(dialog.getByLabel('Base URL', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('provider-api.png'), fullPage: true, animations: 'disabled' })
  await dialog.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('combobox', { name: '筛选类型', exact: true }).click()
  await page.getByRole('option', { name: 'API', exact: true }).click()
  await expect(page.getByRole('cell', { name: 'Routing API', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Routing Group', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '编辑 Routing API', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: '编辑API账号', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog').getByRole('combobox', { name: '类型', exact: true })).toHaveCount(0)
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('combobox', { name: '筛选类型', exact: true }).click()
  await page.getByRole('option', { name: '全部类型', exact: true }).click()
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('provider-list.png'), fullPage: true, animations: 'disabled' })

  await page.getByRole('link', { name: '模型供应商', exact: true }).click()
  await expect(page).toHaveURL(/#suppliers$/)
  await expect(page.getByRole('heading', { name: '模型供应商', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('form', { name: '供应商配置' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: /查看.*详情/ })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('supplier-list.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('row', { name: '查看 Anthropic 详情', exact: true }).click()
  await expect(page).toHaveURL(/#suppliers\/anthropic$/)
  await expect(page.getByRole('dialog', { name: '模型供应商 Anthropic', exact: true })).toBeVisible()
  dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('Claude URL', { exact: true })).toHaveText('https://api.anthropic.com/v1')
  await expect(dialog.getByRole('form', { name: '供应商配置', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page).toHaveURL(/#suppliers$/)
  await page.getByRole('row', { name: '查看 Kimi 详情', exact: true }).press('Enter')
  await expect(page).toHaveURL(/#suppliers\/kimi$/)
  await expect(dialog.getByLabel('OpenAI URL', { exact: true })).toHaveText('https://api.moonshot.cn/v1')
  await page.reload()
  dialog = page.getByRole('dialog', { name: '模型供应商 Kimi', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByLabel('Claude URL', { exact: true })).toHaveText('https://api.moonshot.cn/anthropic/v1')
  await page.screenshot({ path: testInfo.outputPath('supplier-detail.png'), fullPage: true, animations: 'disabled' })
  const value = await (await page.request.get('/api/suppliers')).json()
  expect(value.suppliers).toHaveLength(7)
  for (const supplier of value.suppliers) {
    expect(supplier).toEqual(expect.objectContaining({
      id: expect.any(String),
      name: expect.any(String),
      claude_url: expect.any(String),
      openai_url: expect.any(String),
      models: expect.any(Array),
      supported_clients: expect.any(Array),
    }))
    expect(supplier).not.toHaveProperty('codex_url')
  }
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page).toHaveURL(/#suppliers$/)
  const providers = await (await page.request.get('/api/accounts')).json()
  const group = providers.items.find((p: { name: string }) => p.name === 'Routing Group')
  expect(group.config.client_type).toBe('claude')
  expect(group.config.client_types).toBeUndefined()
})
