import { expect, test } from '@playwright/test'

test('provider quota supports cache reads and refresh without group quota', async ({ page }, testInfo) => {
  const cacheReads: string[] = []
  page.on('request', request => {
    if (request.url().includes('/quota') || (request.method() === 'GET' && request.url().includes('/refresh-quota'))) cacheReads.push(request.url())
  })
  await page.goto('/')
  await page.getByLabel('用户名', { exact: true }).fill('e2e-admin')
  await page.getByLabel('密码', { exact: true }).fill('e2e-admin-password')
  await page.getByRole('button', { name: '登录控制台' }).click()
  await expect(page.getByRole('heading', { name: '个人总览', exact: true })).toBeVisible()
  const demoResponse = await page.request.post('/api/ai-providers', { data: { name: 'Usage Demo', provider: 'dummy', config: { kind: 'subscription', supplier: 'dummy', subscription_plan: 'claude_pro', enabled: true } } })
  expect(demoResponse.status()).toBe(201)
  const demo = await demoResponse.json()
  const realResponse = await page.request.post('/api/ai-providers', { data: { name: 'Usage Real', provider: 'openai', config: { kind: 'subscription', supplier: 'openai', subscription_plan: 'codex_plus', enabled: true, credential: { access_token: 'e2e-not-a-real-token' } } } })
  expect(realResponse.status()).toBe(201)
  const real = await realResponse.json()
  const groupResponse = await page.request.post('/api/ai-providers', { data: { name: 'Usage Group', provider: 'group', config: { kind: 'group', enabled: true, members: [{ id: demo.id, weight: 3 }, { id: real.id, weight: 3 }] } } })
  expect(groupResponse.status()).toBe(201)
  await page.reload()
  await page.getByRole('button', { name: '账号管理', exact: true }).click()
  const demoRow = page.getByRole('row', { name: '查看 Usage Demo 详情', exact: true })
  await expect(page.getByRole('columnheader', { name: '额度' })).toBeVisible()
  await expect(page.getByRole('button', { name: '查看 Usage Demo 额度' })).toHaveCount(0)
  await expect(demoRow.getByText('未知', { exact: true })).toBeVisible()
  await demoRow.getByRole('button', { name: '刷新 Usage Demo 额度' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(demoRow.getByText('5h', { exact: true })).toBeVisible()
  await expect(demoRow.getByText('周', { exact: true })).toBeVisible()
  await expect(demoRow.locator('dl > div')).toHaveCount(2)
  await expect(demoRow.getByText('重置时间', { exact: false })).toHaveCount(0)
  const cachedValue = await demoRow.locator('dd').first().innerText()
  expect(cachedValue).toMatch(/\d+%/)
  await page.screenshot({ path: testInfo.outputPath('dummy-usage.png'), fullPage: true })
  await page.reload()
  await expect(demoRow.locator('dd').first()).toHaveText(cachedValue, { useInnerText: true })
  const groupRow = page.getByRole('row', { name: '查看 Usage Group 详情', exact: true })
  await expect(groupRow.getByRole('button', { name: '刷新 Usage Group 额度' })).toHaveCount(0)
  await expect(groupRow.locator('td').nth(6)).toBeEmpty()
  const rejected = await page.request.post(`/api/ai-providers/${(await groupResponse.json()).id}/refresh-quota`)
  expect(rejected.status()).toBe(501)
  const list = await (await page.request.get('/api/ai-providers')).json()
  expect(list.items.find((item: { provider: string }) => item.provider === 'group')).not.toHaveProperty('quota')
  await expect(demoRow.locator('dd').first()).toHaveText(cachedValue, { useInnerText: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('group-without-quota-mobile.png'), fullPage: true })
  expect(cacheReads).toEqual([])
})
