package aiprovider2

import (
	"errors"

	"ai-unisub/internal/common"
)

var (
	ErrAccountNotFound     = errors.New("account not found")
	ErrAuthentication      = errors.New("supplier authentication failed")
	ErrGatewayForbidden    = errors.New("gateway access forbidden")
	ErrGatewayUnauthorized = errors.New("gateway authentication failed")
	ErrInvalidResponse     = errors.New("invalid supplier response")
	ErrModelsUnsupported   = errors.New("supplier does not support model listing")
	ErrQueueTimeout        = errors.New(common.MessageAIProviderQueueTimeout)
	ErrQuotaNotConfigured  = errors.New("quota credentials or endpoint are not configured")
	ErrQuotaUnsupported    = errors.New("supplier does not support quota queries")
	ErrRateLimited         = errors.New("supplier request rate limited")
	ErrSupplierNotFound    = errors.New("supplier not found")
	ErrUnavailable         = errors.New(common.MessageAIProviderUnavailable)
	ErrUpstream            = errors.New("supplier upstream request failed")

	errAccountAPIKeyEmpty                   = errors.New("account API key is empty")
	errAccountAndResponseRequired           = errors.New("account and response are required")
	errAccountDoesNotProvideAccessToken     = errors.New("account does not provide an access token")
	errAccountGroupCycle                    = errors.New("account group cycle detected")
	errAccountGroupSchedulerNotConfigured   = errors.New("account group scheduler is not configured")
	errAccountLimitsOrProxyGroupNegative    = errors.New("account limits and proxy group ID must not be negative")
	errAccountManagerNotConfigured          = errors.New("account manager is not configured")
	errAccountManagerRequired               = errors.New("account manager is required")
	errAccountNameRequired                  = errors.New("account name is required")
	errAccountRequired                      = errors.New("account is required")
	errAccountRequestAndBodyRequired        = errors.New("account, request, and body are required")
	errAccountSupplierMismatch              = errors.New("account supplier does not match request supplier")
	errAPIAccountAPIKeyRequired             = errors.New("API account api_key is required")
	errAPIAccountHasSubscriptionFields      = errors.New("API account cannot contain subscription fields")
	errClientAPIKeyRequired                 = errors.New("client API key is required")
	errContextAccountAndRequestRequired     = errors.New("context, account, and request are required")
	errContextRequired                      = errors.New("context is required")
	errDatabaseRequired                     = errors.New("database is required")
	errDuplicateGroupMember                 = errors.New("duplicate group member")
	errDuplicateSubscriptionWeight          = errors.New("duplicate subscription weight")
	errDuplicateSupplierModel               = errors.New("duplicate supplier model")
	errGatewayAuthListenerRequired          = errors.New("gateway auth listener is required")
	errGatewayAuthNoAccountOrSupplier       = errors.New("gateway authentication returned no account or supplier")
	errGatewayAuthUnresolvedGroupAccount    = errors.New("gateway authentication returned an unresolved group account")
	errGatewayRequestBodyExceedsLimit       = errors.New("gateway request body exceeds limit")
	errGroupAccountHasSupplierConfiguration = errors.New("group account cannot own supplier credentials or endpoint")
	errGroupAccountRequiresMembers          = errors.New("group account requires members")
	errGroupMemberIDOrWeightInvalid         = errors.New("group member ID and weight must be positive")
	errInvalidAccountKind                   = errors.New("invalid account kind")
	errInvalidAPIEndpoint                   = errors.New("invalid API endpoint")
	errInvalidClientType                    = errors.New("invalid client type")
	errInvalidGatewayRequest                = errors.New("invalid gateway request")
	errInvalidUpstreamEndpoint              = errors.New("invalid upstream endpoint")
	errManagerNil                           = errors.New("manager is nil")
	errModelMappingInvalid                  = errors.New("model mapping pattern and target must be non-empty without surrounding whitespace")
	errModelMappingTargetInvalid            = errors.New("model mapping target must be a valid supplier model")
	errOAuthAccountAccessTokenRequired      = errors.New("OAuth account credential access token is required")
	errOAuthAccountHasAPIKey                = errors.New("OAuth account cannot contain an API key")
	errOAuthCredentialNoAccessToken         = errors.New("OAuth credential has no access token")
	errOAuthManagerNotConfigured            = errors.New("OAuth manager is not configured")
	errOnlyGroupAccountsMayHaveMembers      = errors.New("only group accounts may contain members")
	errProviderManagerDatabaseNotConfigured = errors.New("provider manager database is not configured")
	errProviderManagerNotConfigured         = errors.New("provider manager is not configured")
	errProxyManagerRequired                 = errors.New("proxy manager is required")
	errRequestBodyNotReplayable             = errors.New("request body cannot be replayed")
	errRequestRequired                      = errors.New("request is required")
	errRequestURLRequired                   = errors.New("request URL is required")
	errSubscriptionWeightInvalid            = errors.New("subscription weight must be positive and named")
	errSupplierEmptyAccessToken             = errors.New("supplier returned an empty access token")
	errSupplierManagerNotConfigured         = errors.New("supplier manager is not configured")
	errSupplierModelEmpty                   = errors.New("supplier model must not be empty")
	errSupplierNoAPIBaseURL                 = errors.New("supplier has no API base URL for the request protocol")
	errSupplierProxyManagerNotConfigured    = errors.New("supplier proxy manager is not configured")
	errSupplierURLsImmutable                = errors.New("supplier URLs are built in and cannot be changed")
	errUnknownSupplier                      = errors.New("unknown supplier")
	errUpstreamNilResponse                  = errors.New("upstream returned a nil response")
)
