package server

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func (s *Server) adminPage(c *gin.Context) {
	c.Header("Cache-Control", "no-store")
	c.Header("X-Content-Type-Options", "nosniff")
	c.Data(http.StatusOK, "text/html; charset=utf-8", []byte(adminHTML))
}

const adminHTML = `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="dark">
  <title>UniSub · 服务器集成控制台</title>
  <style>
    :root{--bg:#090d18;--panel:#111725;--panel2:#151d2d;--line:#263147;--text:#f4f7fb;--muted:#8e9bb0;--green:#5ee6a8;--cyan:#58c9e8;--orange:#ffb86b;--red:#ff7285;--shadow:0 20px 60px #0006}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 85% 0,#17334a55,transparent 30%),radial-gradient(circle at 0 100%,#18352b44,transparent 34%),var(--bg);color:var(--text);font:14px/1.5 Inter,"Segoe UI",system-ui,sans-serif;min-height:100vh}button,input,select,textarea{font:inherit}button{cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}[hidden]{display:none!important}
    .login-shell{min-height:100vh;display:grid;grid-template-columns:1.08fr .92fr}.login-art{position:relative;overflow:hidden;padding:64px;display:flex;flex-direction:column;justify-content:space-between;border-right:1px solid var(--line)}.login-art:after{content:"";position:absolute;width:520px;height:520px;border:1px solid #5ee6a833;border-radius:50%;right:-160px;bottom:-210px;box-shadow:0 0 0 70px #58c9e80b,0 0 0 140px #5ee6a808}.brand{display:flex;gap:12px;align-items:center;font-weight:800;letter-spacing:.2px;font-size:17px;position:relative;z-index:1}.brand-mark{width:34px;height:34px;border-radius:10px;background:linear-gradient(135deg,var(--green),var(--cyan));display:grid;place-items:center;color:#07120f;box-shadow:0 0 30px #5ee6a844}.hero{max-width:650px;position:relative;z-index:1}.eyebrow{color:var(--green);font-weight:700;text-transform:uppercase;letter-spacing:2px;font-size:11px}.hero h1{font-size:clamp(42px,6vw,78px);line-height:1.02;letter-spacing:-4px;margin:18px 0 24px}.hero h1 span{color:transparent;-webkit-text-stroke:1px #9fb0c8}.hero p{max-width:560px;color:#aeb9c9;font-size:17px}.signal{display:flex;gap:32px;color:var(--muted);position:relative;z-index:1}.signal b{display:block;color:var(--text);font-size:21px}.login-side{display:grid;place-items:center;padding:32px}.login-card{width:min(420px,100%)}.login-card h2{font-size:28px;margin:0 0 8px}.login-card>p{color:var(--muted);margin:0 0 32px}
    label{display:block;color:#b8c3d4;font-size:12px;font-weight:650;margin:0 0 8px}.field{margin:0 0 18px}.input,select,textarea{width:100%;border:1px solid var(--line);background:#0d1320;color:var(--text);border-radius:10px;padding:12px 14px;outline:none;transition:.2s}.input:focus,select:focus,textarea:focus{border-color:#5ee6a888;box-shadow:0 0 0 3px #5ee6a811}textarea{resize:vertical;min-height:110px}.btn{border:1px solid var(--line);background:#182132;color:var(--text);border-radius:9px;padding:10px 14px;font-weight:700;transition:.18s}.btn:hover{border-color:#4c5e7a;transform:translateY(-1px)}.btn-primary{background:var(--green);border-color:var(--green);color:#07140f}.btn-danger{color:#ff9ba8}.btn-ghost{background:transparent}.btn-block{width:100%;padding:13px}.login-error{color:#ff9baa;margin:10px 0 0;min-height:21px}.secure-note{display:flex;gap:10px;color:var(--muted);font-size:12px;margin-top:24px}.dot{width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 10px var(--green);display:inline-block}
    .app{min-height:100vh;display:grid;grid-template-columns:242px minmax(0,1fr)}.sidebar{border-right:1px solid var(--line);background:#0c111d;padding:26px 18px;position:sticky;top:0;height:100vh;display:flex;flex-direction:column}.sidebar .brand{padding:0 8px 28px}.nav{display:grid;gap:5px}.nav button{border:0;background:transparent;color:#8996aa;padding:11px 13px;text-align:left;border-radius:8px;display:flex;gap:11px;align-items:center}.nav button:hover{color:var(--text);background:#141c2a}.nav button.active{color:var(--green);background:#5ee6a811}.nav svg{width:18px;height:18px}.side-bottom{margin-top:auto;border-top:1px solid var(--line);padding-top:18px}.server-state{display:flex;align-items:center;gap:10px;padding:0 8px 16px}.server-state small{display:block;color:var(--muted)}
    .main{min-width:0}.topbar{height:82px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 34px;position:sticky;top:0;background:#090d18e8;backdrop-filter:blur(14px);z-index:5}.crumb{color:var(--muted)}.crumb b{color:var(--text)}.top-actions{display:flex;align-items:center;gap:10px}.icon-btn{width:39px;height:39px;display:grid;place-items:center;padding:0}.content{padding:34px;max-width:1460px;margin:auto}.page-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:28px}.page-head h1{font-size:30px;letter-spacing:-1px;margin:0 0 5px}.page-head p{color:var(--muted);margin:0}.grid{display:grid;gap:18px}.stats{grid-template-columns:repeat(4,1fr);margin-bottom:18px}.card{background:linear-gradient(145deg,#121928,#0f1521);border:1px solid var(--line);border-radius:13px;padding:20px;box-shadow:0 8px 28px #0002}.stat{position:relative;overflow:hidden}.stat:after{content:"";position:absolute;width:84px;height:84px;border-radius:50%;background:var(--glow,#5ee6a8);filter:blur(55px);opacity:.22;right:-18px;top:-18px}.stat-label{color:var(--muted);font-size:12px}.stat-value{font-size:30px;font-weight:800;letter-spacing:-1px;margin:9px 0 2px}.stat-detail{font-size:12px;color:#79879b}.split{grid-template-columns:minmax(0,1.45fr) minmax(290px,.55fr)}.card-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px}.card-head h2{font-size:16px;margin:0}.card-head span{font-size:12px;color:var(--muted)}
    .providers{display:grid;gap:12px}.provider-row{display:grid;grid-template-columns:128px minmax(0,1fr) 56px;gap:14px;align-items:center}.provider-name{display:flex;gap:9px;align-items:center;font-weight:650}.provider-logo{width:26px;height:26px;border-radius:7px;display:grid;place-items:center;font-size:11px;font-weight:900}.claude{background:#df8854;color:#251107}.codex{background:#eaf1ee;color:#10251e}.grok{background:#222b3a;color:#d5deed}.bar{height:7px;background:#222c3c;border-radius:99px;overflow:hidden}.bar i{height:100%;display:block;border-radius:99px;background:linear-gradient(90deg,var(--green),var(--cyan))}.provider-count{text-align:right;color:var(--muted)}.activity{display:grid;gap:0}.activity-item{display:grid;grid-template-columns:8px 1fr auto;gap:12px;align-items:start;padding:12px 0;border-bottom:1px solid #202a3b}.activity-item:last-child{border:0}.activity-item p{margin:0;font-weight:650}.activity-item small{color:var(--muted)}.empty{padding:30px 15px;text-align:center;color:var(--muted)}
    .table-card{padding:0;overflow:hidden}.table-tools{display:flex;gap:12px;padding:18px;border-bottom:1px solid var(--line)}.search{flex:1;position:relative}.search .input{padding-left:39px}.search svg{position:absolute;left:13px;top:12px;color:#748196}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:840px}th{padding:12px 18px;color:#768399;font-size:11px;letter-spacing:.6px;text-transform:uppercase;text-align:left;background:#0d1420}td{padding:15px 18px;border-top:1px solid #202a3a;vertical-align:middle}.account-name{font-weight:750}.subtle{color:var(--muted);font-size:12px}.badge{display:inline-flex;gap:6px;align-items:center;border:1px solid #344156;border-radius:99px;padding:4px 8px;font-size:11px}.badge.ok{color:#75e9b3;border-color:#285d49;background:#17362966}.badge.off{color:#a2adbd}.badge.warn{color:#ffc481;border-color:#6b4d2e;background:#3d291866}.actions{display:flex;justify-content:flex-end;gap:5px}.actions button{border:0;background:transparent;color:#8794a8;padding:6px;border-radius:6px}.actions button:hover{background:#1c2636;color:white}.key{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;color:#b6c2d4}
    .integration-grid{grid-template-columns:repeat(3,1fr)}.integration-card{position:relative}.integration-card.selected{border-color:#5ee6a877}.integration-card h3{display:flex;align-items:center;gap:11px;margin:0 0 8px}.integration-card p{color:var(--muted);font-size:13px;min-height:42px}.endpoint{background:#090e18;border:1px solid #202b3d;border-radius:8px;padding:11px 12px;font:12px ui-monospace,Consolas,monospace;color:#aab8ca;word-break:break-all;margin:16px 0}.copy-row{display:flex;gap:8px}.copy-row .btn{flex:1}.code-card{margin-top:18px}.code-tabs{display:flex;gap:4px;margin-bottom:12px}.code-tabs button{border:0;background:transparent;color:var(--muted);padding:8px 11px;border-radius:7px}.code-tabs button.active{background:#1c2636;color:var(--green)}pre{margin:0;background:#080c14;border:1px solid #202a39;border-radius:9px;padding:18px;color:#c4d0df;overflow:auto;white-space:pre-wrap;word-break:break-all;font:12.5px/1.7 ui-monospace,Consolas,monospace}.code-green{color:var(--green)}
    .settings{max-width:690px}.settings .card{margin-bottom:18px}.settings h2{margin:0 0 5px;font-size:17px}.settings p{color:var(--muted);margin:0 0 22px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.form-actions{display:flex;justify-content:flex-end;margin-top:18px}.modal-shell{position:fixed;inset:0;background:#03060bbd;backdrop-filter:blur(5px);display:grid;place-items:center;padding:20px;z-index:20}.modal{width:min(620px,100%);max-height:92vh;overflow:auto;background:#111827;border:1px solid #344158;border-radius:15px;box-shadow:var(--shadow)}.modal-head{padding:20px 22px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}.modal-head h2{font-size:19px;margin:0}.modal-body{padding:22px}.modal-foot{padding:16px 22px;border-top:1px solid var(--line);display:flex;justify-content:flex-end;gap:9px}.close{border:0;background:transparent;color:var(--muted);font-size:22px}.notice{border:1px solid #765b2d;background:#3a2b1766;color:#ffd18c;padding:12px;border-radius:9px;margin-bottom:16px}.secret{display:flex;gap:8px}.secret .input{font-family:ui-monospace,Consolas,monospace}.toast-stack{position:fixed;right:22px;bottom:22px;display:grid;gap:9px;z-index:50}.toast{background:#172131;border:1px solid #3a4961;border-radius:9px;padding:12px 15px;box-shadow:var(--shadow);animation:in .2s ease;max-width:360px}.toast.error{border-color:#733c49;color:#ffadba}@keyframes in{from{transform:translateY(8px);opacity:0}}
    @media(max-width:1050px){.stats{grid-template-columns:1fr 1fr}.split{grid-template-columns:1fr}.integration-grid{grid-template-columns:1fr}.login-shell{grid-template-columns:1fr}.login-art{display:none}.app{grid-template-columns:78px}.sidebar{padding:25px 12px}.sidebar .brand span,.nav span,.side-bottom .server-copy{display:none}.sidebar .brand{justify-content:center;padding-left:0;padding-right:0}.nav button{justify-content:center}.server-state{justify-content:center}.content{padding:25px}.topbar{padding:0 25px}}
    @media(max-width:650px){.app{display:block}.sidebar{height:64px;width:100%;position:fixed;top:auto;bottom:0;z-index:10;border-right:0;border-top:1px solid var(--line);padding:7px 12px}.sidebar .brand,.side-bottom{display:none}.nav{grid-template-columns:repeat(4,1fr)}.nav button{padding:10px}.topbar{height:65px;padding:0 16px}.content{padding:20px 15px 86px}.stats{grid-template-columns:1fr 1fr;gap:10px}.card{padding:16px}.stat-value{font-size:25px}.page-head{align-items:flex-start;flex-direction:column}.form-grid{grid-template-columns:1fr}.provider-row{grid-template-columns:105px 1fr 42px}.top-actions .refresh-label{display:none}}
  </style>
</head>
<body>
  <section class="login-shell" id="loginView">
    <div class="login-art">
      <div class="brand"><span class="brand-mark">∪</span><span>UNISUB</span></div>
      <div class="hero"><div class="eyebrow">Unified subscription gateway</div><h1>一个入口<br><span>连接所有模型</span></h1><p>将 Claude、Codex 与 Grok 订阅账号安全集成到你的服务器，在一个控制台管理凭据、访问密钥与用量。</p></div>
      <div class="signal"><div><b>3</b>原生协议</div><div><b>AES-256</b>凭据加密</div><div><b>SSE</b>流式透传</div></div>
    </div>
    <div class="login-side"><form class="login-card" id="loginForm"><div class="eyebrow">管理员区域</div><h2>登录服务器</h2><p>使用管理员凭据进入 UniSub 集成控制台。</p><div class="field"><label for="username">用户名</label><input class="input" id="username" autocomplete="username" value="admin" required></div><div class="field"><label for="password">密码</label><input class="input" id="password" type="password" autocomplete="current-password" required></div><button class="btn btn-primary btn-block" id="loginButton" type="submit">安全登录</button><div class="login-error" id="loginError"></div><div class="secure-note"><span class="dot"></span><span>JWT 仅保存在当前浏览器会话，关闭页面后自动清除。</span></div></form></div>
  </section>

  <div class="app" id="appView" hidden>
    <aside class="sidebar"><div class="brand"><span class="brand-mark">∪</span><span>UNISUB</span></div><nav class="nav">
      <button class="active" data-page="overview" title="总览"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg><span>总览</span></button>
      <button data-page="accounts" title="账号"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0116 0"/></svg><span>账号管理</span></button>
      <button data-page="integration" title="集成"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M8 12h8M12 8v8"/><rect x="3" y="3" width="18" height="18" rx="4"/></svg><span>服务器集成</span></button>
      <button data-page="settings" title="设置"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 00.3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 00-1.9-.3 1.7 1.7 0 00-1 1.6v.2h-4V21a1.7 1.7 0 00-1-1.6 1.7 1.7 0 00-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 00.3-1.9A1.7 1.7 0 003 14H2.8v-4H3a1.7 1.7 0 001.6-1 1.7 1.7 0 00-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 009 4.6 1.7 1.7 0 0010 3V2.8h4V3a1.7 1.7 0 001 1.6 1.7 1.7 0 001.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 00-.3 1.9 1.7 1.7 0 001.6 1h.2v4H21a1.7 1.7 0 00-1.6 1z"/></svg><span>安全设置</span></button>
    </nav><div class="side-bottom"><div class="server-state"><span class="dot"></span><div class="server-copy"><b>服务运行中</b><small id="serverHost"></small></div></div><button class="btn btn-ghost btn-block" id="logoutButton">退出登录</button></div></aside>
    <main class="main"><header class="topbar"><div class="crumb">UniSub / <b id="crumbText">总览</b></div><div class="top-actions"><button class="btn icon-btn" id="refreshButton" title="刷新">↻</button><button class="btn btn-primary" id="topAddButton"><span class="refresh-label">＋ 添加账号</span><span class="mobile-add" hidden>＋</span></button></div></header>
      <div class="content">
        <section class="page" id="page-overview"><div class="page-head"><div><h1>服务器总览</h1><p>所有上游订阅账号的运行状态和本地 24 小时用量。</p></div><span class="badge ok"><span class="dot"></span> Gateway healthy</span></div>
          <div class="grid stats"><div class="card stat"><div class="stat-label">已接入账号</div><div class="stat-value" id="statAccounts">—</div><div class="stat-detail" id="statEnabled">正在加载</div></div><div class="card stat" style="--glow:#58c9e8"><div class="stat-label">24h 请求</div><div class="stat-value" id="statRequests">—</div><div class="stat-detail">所有上游合计</div></div><div class="card stat" style="--glow:#ffb86b"><div class="stat-label">24h 输入 Token</div><div class="stat-value" id="statInput">—</div><div class="stat-detail">本地用量统计</div></div><div class="card stat" style="--glow:#b49cff"><div class="stat-label">24h 输出 Token</div><div class="stat-value" id="statOutput">—</div><div class="stat-detail">本地用量统计</div></div></div>
          <div class="grid split"><div class="card"><div class="card-head"><h2>平台分布</h2><span>按账号数量</span></div><div class="providers" id="providerBars"></div></div><div class="card"><div class="card-head"><h2>最近状态</h2><span>Latest</span></div><div class="activity" id="recentActivity"></div></div></div>
        </section>
        <section class="page" id="page-accounts" hidden><div class="page-head"><div><h1>账号管理</h1><p>管理上游凭据、下游 API Key 和账号访问状态。</p></div><button class="btn btn-primary" id="pageAddButton">＋ 添加账号</button></div><div class="card table-card"><div class="table-tools"><div class="search"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="M20 20l-4-4"/></svg><input class="input" id="accountSearch" placeholder="搜索名称、平台或 Key 前缀"></div><select id="providerFilter" style="width:150px"><option value="">全部平台</option><option value="claude">Claude</option><option value="codex">Codex</option><option value="grok">Grok</option></select></div><div class="table-wrap" id="accountTable"></div></div></section>
        <section class="page" id="page-integration" hidden><div class="page-head"><div><h1>服务器集成</h1><p>选择协议并复制基础地址，将 UniSub 接入你的应用。</p></div></div><div class="grid integration-grid" id="integrationCards"></div><div class="card code-card"><div class="card-head"><h2>快速调用</h2><span>请替换为账号创建时显示的 Key</span></div><div class="code-tabs"><button class="active" data-code="curl">cURL</button><button data-code="python">Python</button><button data-code="js">JavaScript</button></div><pre id="codeSample"></pre></div></section>
        <section class="page settings" id="page-settings" hidden><div class="page-head"><div><h1>安全设置</h1><p>更新当前管理员密码。</p></div></div><form class="card" id="passwordForm"><h2>修改管理员密码</h2><p>修改后，现有 JWT 在过期前仍然有效。新密码至少 12 个字符。</p><div class="field"><label>当前密码</label><input class="input" id="currentPassword" type="password" autocomplete="current-password" required></div><div class="form-grid"><div class="field"><label>新密码</label><input class="input" id="newPassword" type="password" minlength="12" autocomplete="new-password" required></div><div class="field"><label>确认新密码</label><input class="input" id="confirmPassword" type="password" minlength="12" autocomplete="new-password" required></div></div><div class="form-actions"><button class="btn btn-primary" type="submit">保存新密码</button></div></form><div class="card"><h2>安全边界</h2><p style="margin-bottom:0">生产环境请将管理入口限制在可信网段，并通过启用 TLS 的反向代理对外提供服务。上游凭据由 AES-256-GCM 加密保存，不会通过管理 API 回显。</p></div></section>
      </div>
    </main>
  </div>

  <div class="modal-shell" id="accountModal" hidden><form class="modal" id="accountForm"><div class="modal-head"><h2>接入上游账号</h2><button type="button" class="close" data-close>&times;</button></div><div class="modal-body"><div class="form-grid"><div class="field"><label>账号名称</label><input class="input" id="accountName" placeholder="例如：codex-plus-main" required></div><div class="field"><label>平台</label><select id="accountProvider"><option value="claude">Claude</option><option value="codex">Codex</option><option value="grok">Grok</option></select></div><div class="field"><label>鉴权方式</label><select id="authType"><option value="oauth">OAuth Token</option><option value="api_key">API Key</option></select></div><div class="field"><label>并发限制</label><input class="input" id="concurrencyLimit" type="number" value="1" min="1" max="100"></div><div class="field"><label>RPM 限制（可选）</label><input class="input" id="rpmLimit" type="number" min="1" placeholder="例如 30"></div><div class="field"><label>Token 过期时间（可选）</label><input class="input" id="tokenExpiresAt" type="datetime-local"></div></div><div class="field"><label>凭据 JSON</label><textarea id="credentials" spellcheck="false" placeholder='{"access_token":"..."}' required></textarea><div class="subtle" id="credentialHint">Codex OAuth 需要 access_token 和 chatgpt_account_id。</div></div></div><div class="modal-foot"><button type="button" class="btn btn-ghost" data-close>取消</button><button type="submit" class="btn btn-primary" id="createButton">创建账号</button></div></form></div>
  <div class="modal-shell" id="keyModal" hidden><div class="modal"><div class="modal-head"><h2 id="keyTitle">保存 API Key</h2><button class="close" data-key-close>&times;</button></div><div class="modal-body"><div class="notice">该 Key 只显示这一次。关闭窗口前请复制并安全保存。</div><div class="secret"><input class="input" id="newAPIKey" readonly><button class="btn btn-primary" id="copyKeyButton">复制</button></div></div><div class="modal-foot"><button class="btn" data-key-close>我已保存</button></div></div></div>
  <div class="toast-stack" id="toastStack"></div>

  <script>
    (function(){
      'use strict';
      var token=sessionStorage.getItem('unisub_admin_token')||'';
      var accounts=[];var usage={};var selectedProvider='codex';var selectedCode='curl';
      var names={overview:'总览',accounts:'账号管理',integration:'服务器集成',settings:'安全设置'};
      function $(id){return document.getElementById(id)}
      function escapeHTML(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
      function formatNumber(value){return new Intl.NumberFormat('zh-CN',{notation:Number(value)>=10000?'compact':'standard',maximumFractionDigits:1}).format(Number(value)||0)}
      function formatTime(value){if(!value)return '尚未使用';var d=new Date(value);return isNaN(d)?'—':d.toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
      function toast(message,error){var el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;$('toastStack').appendChild(el);setTimeout(function(){el.remove()},3200)}
      async function request(path,options){options=options||{};options.headers=Object.assign({},options.headers||{},{Authorization:'Bearer '+token,'Content-Type':'application/json'});var response=await fetch(path,options);if(response.status===204)return null;var body={};try{body=await response.json()}catch(e){}if(response.status===401){logout();throw new Error('会话已过期，请重新登录')}if(!response.ok)throw new Error(body.error&&body.error.message||response.statusText);return body}
      function logout(){token='';sessionStorage.removeItem('unisub_admin_token');$('appView').hidden=true;$('loginView').hidden=false;$('password').value=''}
      async function login(event){event.preventDefault();var button=$('loginButton');button.disabled=true;$('loginError').textContent='';try{var response=await fetch('/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});var body=await response.json();if(!response.ok)throw new Error(body.error&&body.error.message||'登录失败');token=body.token;sessionStorage.setItem('unisub_admin_token',token);showApp()}catch(e){$('loginError').textContent=e.message}finally{button.disabled=false}}
      function showApp(){$('loginView').hidden=true;$('appView').hidden=false;$('serverHost').textContent=location.host;loadData()}
      function navigate(page){document.querySelectorAll('.page').forEach(function(el){el.hidden=el.id!=='page-'+page});document.querySelectorAll('.nav button').forEach(function(el){el.classList.toggle('active',el.dataset.page===page)});$('crumbText').textContent=names[page];$('topAddButton').hidden=page==='settings';if(page==='integration')renderIntegrations()}
      async function loadData(){try{var result=await request('/admin/accounts');accounts=result.data||[];var pairs=await Promise.all(accounts.map(async function(a){try{return [a.id,await request('/admin/accounts/'+a.id+'/usage')]}catch(e){return [a.id,null]}}));usage={};pairs.forEach(function(pair){if(pair[1])usage[pair[0]]=pair[1]});renderOverview();renderAccounts()}catch(e){toast(e.message,true)}}
      function totals(){var out={requests:0,input:0,output:0};Object.keys(usage).forEach(function(id){var local=usage[id]&&usage[id].local_usage||{};out.requests+=Number(local.requests_24h)||0;out.input+=Number(local.input_tokens_24h)||0;out.output+=Number(local.output_tokens_24h)||0});return out}
      function providerIcon(p){return '<span class="provider-logo '+escapeHTML(p)+'">'+({claude:'C',codex:'O',grok:'G'}[p]||'?')+'</span>'}
      function renderOverview(){var t=totals();$('statAccounts').textContent=formatNumber(accounts.length);$('statEnabled').textContent=accounts.filter(function(a){return a.enabled}).length+' 个已启用';$('statRequests').textContent=formatNumber(t.requests);$('statInput').textContent=formatNumber(t.input);$('statOutput').textContent=formatNumber(t.output);var counts={claude:0,codex:0,grok:0};accounts.forEach(function(a){counts[a.provider]=(counts[a.provider]||0)+1});var max=Math.max(1,counts.claude,counts.codex,counts.grok);$('providerBars').innerHTML=['claude','codex','grok'].map(function(p){return '<div class="provider-row"><div class="provider-name">'+providerIcon(p)+p.charAt(0).toUpperCase()+p.slice(1)+'</div><div class="bar"><i style="width:'+Math.round(counts[p]/max*100)+'%"></i></div><div class="provider-count">'+counts[p]+'</div></div>'}).join('');var recent=accounts.slice().sort(function(a,b){return new Date(b.last_used_at||b.created_at)-new Date(a.last_used_at||a.created_at)}).slice(0,4);$('recentActivity').innerHTML=recent.length?recent.map(function(a){return '<div class="activity-item"><span class="dot" style="margin-top:7px;background:'+(a.enabled?'var(--green)':'#69768a')+'"></span><div><p>'+escapeHTML(a.name)+'</p><small>'+escapeHTML(a.provider)+' · '+formatTime(a.last_used_at)+'</small></div><span class="badge '+(a.enabled?'ok':'off')+'">'+(a.enabled?'已启用':'已停用')+'</span></div>'}).join(''):'<div class="empty">还没有账号，先接入一个上游订阅吧。</div>'}
      function renderAccounts(){var query=$('accountSearch').value.trim().toLowerCase();var provider=$('providerFilter').value;var filtered=accounts.filter(function(a){return(!provider||a.provider===provider)&&(!query||(a.name+' '+a.provider+' '+a.api_key_prefix).toLowerCase().includes(query))});if(!filtered.length){$('accountTable').innerHTML='<div class="empty">没有匹配的账号。</div>';return}$('accountTable').innerHTML='<table><thead><tr><th>账号</th><th>平台</th><th>状态</th><th>API Key</th><th>24h 请求</th><th>最后使用</th><th style="text-align:right">操作</th></tr></thead><tbody>'+filtered.map(function(a){var u=usage[a.id]&&usage[a.id].local_usage||{};return '<tr><td><div class="account-name">'+escapeHTML(a.name)+'</div><div class="subtle">ID '+a.id+' · '+escapeHTML(a.auth_type)+'</div></td><td><div class="provider-name">'+providerIcon(a.provider)+escapeHTML(a.provider)+'</div></td><td><span class="badge '+(a.enabled?'ok':'off')+'"><span class="dot" style="background:'+(a.enabled?'var(--green)':'#748196')+'"></span>'+(a.enabled?'已启用':'已停用')+'</span></td><td class="key">'+escapeHTML(a.api_key_prefix)+'…</td><td>'+formatNumber(u.requests_24h)+'</td><td class="subtle">'+formatTime(a.last_used_at)+'</td><td><div class="actions"><button title="'+(a.enabled?'停用':'启用')+'" data-action="toggle" data-id="'+a.id+'">'+(a.enabled?'⏸':'▶')+'</button><button title="重置 API Key" data-action="reset" data-id="'+a.id+'">↻</button><button title="删除" data-action="delete" data-id="'+a.id+'" style="color:#ff8796">✕</button></div></td></tr>'}).join('')+'</tbody></table>'}
      function openAccountModal(){$('accountForm').reset();$('concurrencyLimit').value='1';$('credentials').value='';updateCredentialHint();$('accountModal').hidden=false;$('accountName').focus()}
      function closeAccountModal(){$('accountModal').hidden=true}
      function updateCredentialHint(){var p=$('accountProvider').value;var auth=$('authType').value;if(auth==='api_key'){$('credentials').placeholder='{"api_key":"..."}';$('credentialHint').textContent='填入上游平台 API Key。'}else if(p==='codex'){$('credentials').placeholder='{"access_token":"...","refresh_token":"...","chatgpt_account_id":"..."}';$('credentialHint').textContent='Codex OAuth 需要 access_token 和 chatgpt_account_id。'}else{$('credentials').placeholder='{"access_token":"...","refresh_token":"..."}';$('credentialHint').textContent='凭据加密后保存，管理 API 不会回显。'}}
      async function createAccount(event){event.preventDefault();var button=$('createButton');button.disabled=true;try{var credentials=JSON.parse($('credentials').value);var payload={name:$('accountName').value.trim(),provider:$('accountProvider').value,auth_type:$('authType').value,credentials:credentials,concurrency_limit:Number($('concurrencyLimit').value)||1};if($('rpmLimit').value)payload.rpm_limit=Number($('rpmLimit').value);if($('tokenExpiresAt').value)payload.token_expires_at=new Date($('tokenExpiresAt').value).toISOString();var result=await request('/admin/accounts',{method:'POST',body:JSON.stringify(payload)});closeAccountModal();showKey(result.api_key,'账号创建成功');await loadData()}catch(e){toast(e.message,true)}finally{button.disabled=false}}
      function showKey(key,title){$('keyTitle').textContent=title;$('newAPIKey').value=key;$('keyModal').hidden=false}
      async function copyText(text){try{await navigator.clipboard.writeText(text);toast('已复制到剪贴板')}catch(e){var input=document.createElement('textarea');input.value=text;document.body.appendChild(input);input.select();document.execCommand('copy');input.remove();toast('已复制到剪贴板')}}
      async function accountAction(event){var button=event.target.closest('[data-action]');if(!button)return;var id=Number(button.dataset.id);var account=accounts.find(function(a){return a.id===id});if(!account)return;var action=button.dataset.action;if(action==='toggle'){try{await request('/admin/accounts/'+id+'/'+(account.enabled?'disable':'enable'),{method:'POST'});toast(account.enabled?'账号已停用':'账号已启用');await loadData()}catch(e){toast(e.message,true)}}if(action==='reset'){if(!confirm('确定重置 '+account.name+' 的 API Key？旧 Key 将立即失效。'))return;try{var result=await request('/admin/accounts/'+id+'/api-key/reset',{method:'POST'});showKey(result.api_key,'API Key 已重置');await loadData()}catch(e){toast(e.message,true)}}if(action==='delete'){if(!confirm('确定删除 '+account.name+' ？其 API Key 和用量记录也将被删除。'))return;try{await request('/admin/accounts/'+id,{method:'DELETE'});toast('账号已删除');await loadData()}catch(e){toast(e.message,true)}}}
      function integrationData(){var base=location.origin;return[{id:'claude',name:'Claude',desc:'Anthropic Messages 与 Count Tokens 原生透传。',url:base+'/claude/v1'},{id:'codex',name:'Codex',desc:'OpenAI Responses 协议，支持 SSE 实时流。',url:base+'/codex/v1'},{id:'grok',name:'Grok',desc:'xAI Responses 协议原生透传。',url:base+'/grok/v1'}]}
      function renderIntegrations(){$('integrationCards').innerHTML=integrationData().map(function(item){return '<div class="card integration-card '+(item.id===selectedProvider?'selected':'')+'" data-provider="'+item.id+'"><h3>'+providerIcon(item.id)+item.name+'</h3><p>'+item.desc+'</p><div class="endpoint">'+escapeHTML(item.url)+'</div><div class="copy-row"><button class="btn" data-copy="'+escapeHTML(item.url)+'">复制 Base URL</button><button class="btn btn-primary" data-select="'+item.id+'">查看示例</button></div></div>'}).join('');renderCode()}
      function renderCode(){var base=location.origin;var route=selectedProvider==='claude'?'/v1/messages':'/v1/responses';var model=selectedProvider==='claude'?'claude-sonnet-4-5':selectedProvider==='codex'?'gpt-5':'grok-4';var url=base+'/'+selectedProvider+route;var body=selectedProvider==='claude'?'{\n  "model": "'+model+'",\n  "max_tokens": 512,\n  "messages": [{"role": "user", "content": "Hello"}]\n}':'{\n  "model": "'+model+'",\n  "input": "Hello",\n  "stream": true\n}';var samples={curl:'curl '+url+' \\\n  -H "Authorization: Bearer unisub_your_key" \\\n  -H "Content-Type: application/json" \\\n  -d \''+body.replace(/\n/g,' ')+'\'',python:'import requests\n\nresponse = requests.post(\n    "'+url+'",\n    headers={"Authorization": "Bearer unisub_your_key"},\n    json='+body.replace(/"/g,'\'').replace(/true/g,'True')+'\n)\nprint(response.json())',js:'const response = await fetch("'+url+'", {\n  method: "POST",\n  headers: {\n    "Authorization": "Bearer unisub_your_key",\n    "Content-Type": "application/json"\n  },\n  body: JSON.stringify('+body+' )\n});'};$('codeSample').textContent=samples[selectedCode]}
      async function changePassword(event){event.preventDefault();if($('newPassword').value!==$('confirmPassword').value){toast('两次输入的新密码不一致',true);return}try{await request('/admin/password',{method:'PUT',body:JSON.stringify({current_password:$('currentPassword').value,new_password:$('newPassword').value})});$('passwordForm').reset();toast('管理员密码已更新')}catch(e){toast(e.message,true)}}
      $('loginForm').addEventListener('submit',login);$('logoutButton').addEventListener('click',logout);$('refreshButton').addEventListener('click',loadData);$('topAddButton').addEventListener('click',openAccountModal);$('pageAddButton').addEventListener('click',openAccountModal);$('accountForm').addEventListener('submit',createAccount);$('accountProvider').addEventListener('change',updateCredentialHint);$('authType').addEventListener('change',updateCredentialHint);$('accountSearch').addEventListener('input',renderAccounts);$('providerFilter').addEventListener('change',renderAccounts);$('accountTable').addEventListener('click',accountAction);$('passwordForm').addEventListener('submit',changePassword);$('copyKeyButton').addEventListener('click',function(){copyText($('newAPIKey').value)});
      document.querySelectorAll('.nav button').forEach(function(el){el.addEventListener('click',function(){navigate(el.dataset.page)})});document.querySelectorAll('[data-close]').forEach(function(el){el.addEventListener('click',closeAccountModal)});document.querySelectorAll('[data-key-close]').forEach(function(el){el.addEventListener('click',function(){$('keyModal').hidden=true;$('newAPIKey').value=''})});$('integrationCards').addEventListener('click',function(e){var copy=e.target.closest('[data-copy]');if(copy)copyText(copy.dataset.copy);var select=e.target.closest('[data-select]');if(select){selectedProvider=select.dataset.select;renderIntegrations()}});document.querySelectorAll('[data-code]').forEach(function(el){el.addEventListener('click',function(){selectedCode=el.dataset.code;document.querySelectorAll('[data-code]').forEach(function(x){x.classList.toggle('active',x===el)});renderCode()})});
      if(token)showApp();
    })();
  </script>
</body>
</html>`
