import { DetailTableRow } from '@/components/detail-table-row'
import { TableCell } from '@/components/ui/table'
import { AppSelect } from '@/components/app-select'
import { SelectItem } from '@/components/ui/select'
import { useEffect, useId, useState, type MouseEvent } from 'react'
import { Check, Copy, Eye, Plus, Share2, Trash2 } from 'lucide-react'
import { actions, useAction, useKeyConfig, useKeys, useProviderModels, useProviderOptions } from '@/data/store'
import type { APIKey, CCSwitchClient, CCSwitchClientConfig, ClientType, ProviderOption } from '@/data/types'
import { Badge, Confirm, Empty, ErrorMessage, Field, Modal, PageHeader, QueryState, Submit, Table } from '@/components/shared'
import { Button } from '@/components/ui/button'
import { date } from '@/lib/utils'
import { Field as UIField, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Card } from '@/components/ui/card'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { ccSwitchClientLabel, ccSwitchEndpoint, ccSwitchImportForClient, clientsForTypes, publicBaseURL } from '@/lib/cc-switch'

function CopyIconButton({ text, label }: { text: string; label: string }) { const [copied, setCopied] = useState(false); async function copy(event?: MouseEvent) { event?.preventDefault(); event?.stopPropagation(); if (!text) return; try { await navigator.clipboard.writeText(text); setCopied(true); window.setTimeout(() => setCopied(false), 1500) } catch { setCopied(false) } }; return <Button type="button" variant="ghost" size="icon" className="shrink-0 text-muted-foreground" aria-label={copied ? `已复制${label}` : `复制${label}到剪贴板`} disabled={!text} onClick={copy}>{copied ? <Check className="text-emerald-300" /> : <Copy />}</Button> }
function CopyField({ label, value, mono }: { label: string; value: string; mono?: boolean }) { const id = useId(); return <UIField><FieldLabel htmlFor={id}>{label}</FieldLabel><div className="flex items-center gap-1"><Input id={id} readOnly value={value} className={mono ? 'min-w-0 flex-1 font-mono' : 'min-w-0 flex-1'} onFocus={e => e.target.select()} /><CopyIconButton text={value} label={label} /></div></UIField> }
function ReadonlyField({ label, value, mono }: { label: string; value: string; mono?: boolean }) { const id = useId(); return <UIField><FieldLabel htmlFor={id}>{label}</FieldLabel><Input id={id} readOnly value={value} className={mono ? 'font-mono' : undefined} /></UIField> }
function clientTypesOf(key: APIKey, provider?: ProviderOption): ClientType[] { return (key.client_types?.length ? key.client_types : provider?.client_types) || [] }
function CCSwitchIcon({ className }: { className?: string } = {}) { return <Share2 aria-hidden="true" className={className} /> }

export function Keys() {
  const query = useKeys(), accounts = useProviderOptions(), [adding, setAdding] = useState(false), [revealed, setRevealed] = useState<APIKey | null>(null), [exporting, setExporting] = useState<{ key: APIKey; client: CCSwitchClient } | null>(null), [removing, setRemoving] = useState<APIKey | null>(null)
  const remove = useAction(actions.deleteKey, ['keys']), rows = query.data?.items || []
  const providerOf = (key: APIKey) => accounts.data?.items.find(a => a.id === key.account_id)
  return <><PageHeader title="API Key" description="为客户端签发访问密钥，每把 Key 绑定一个账号。" action={<Button onClick={() => setAdding(true)}><Plus />签发 Key</Button>} /><Card><QueryState query={query}>{rows.length ? <Table headers={['名称', '绑定账号', '密钥', '有效期', '操作']}>{rows.map(k => { const provider = providerOf(k); const clients = clientsForTypes(clientTypesOf(k, provider)); return <DetailTableRow key={k.id} aria-label={`查看 ${k.name} 详情`} onOpen={() => setRevealed(k)}><TableCell className="font-medium">{k.name}</TableCell><TableCell><div>{provider?.name || k.account_id}</div>{clientTypesOf(k, provider).length > 0 && <div className="mt-1 text-xs text-muted-foreground">{clientTypesOf(k, provider).join(' · ')}</div>}</TableCell><TableCell className="font-mono text-muted-foreground">••••••••{k.key.slice(-4)}</TableCell><TableCell>{k.expires_at ? <><Badge enabled={Date.parse(k.expires_at) > Date.now()}>{Date.parse(k.expires_at) > Date.now() ? '有效' : '已过期'}</Badge><div className="mt-1 text-xs text-muted-foreground">{date(k.expires_at)}</div></> : <Badge enabled>长期有效</Badge>}</TableCell><TableCell><div className="flex gap-1"><CopyIconButton text={k.key} label={`${k.name} API Key`} />{clients.length > 0 && <CCSwitchClientMenu keyValue={k} clients={clients} onSelect={client => setExporting({ key: k, client })} />}<Button variant="ghost" size="icon" aria-label={`查看 ${k.name}`} onClick={() => setRevealed(k)}><Eye /></Button><Button variant="ghost" size="icon" aria-label={`删除 ${k.name}`} onClick={() => { remove.reset(); setRemoving(k) }}><Trash2 /></Button></div></TableCell></DetailTableRow> })}</Table> : <Empty>暂无 API Key</Empty>}</QueryState></Card>{adding && <KeyForm onClose={() => setAdding(false)} onCreated={k => { setAdding(false); setRevealed(k) }} />}{revealed && <KeyDetails value={revealed} onClose={() => setRevealed(null)} />}{exporting && <CCSwitchExport keyID={exporting.key.id} value={exporting.key} client={exporting.client} onClose={() => setExporting(null)} />}{removing && <Confirm title={`删除密钥「${removing.name}」？`} error={remove.error} pending={remove.isPending} onClose={() => setRemoving(null)} onConfirm={() => remove.mutate(removing.id, { onSuccess: () => setRemoving(null) })} />}</>
}

function CCSwitchClientMenu({ keyValue, clients, onSelect }: { keyValue: APIKey; clients: CCSwitchClient[]; onSelect: (client: CCSwitchClient) => void }) { return <Popover><PopoverTrigger render={<Button variant="ghost" size="icon" aria-label={`导出 ${keyValue.name} 到 CC Switch`} onClick={event => event.stopPropagation()} />}><CCSwitchIcon /></PopoverTrigger><PopoverContent align="start" className="w-48 gap-0.5 p-1">{clients.map(client => <Button key={client} variant="ghost" className="h-8 justify-start px-2 text-xs" onClick={() => onSelect(client)}><CCSwitchIcon />{ccSwitchClientLabel[client]}</Button>)}</PopoverContent></Popover> }

function KeyForm({ onClose, onCreated }: { onClose: () => void; onCreated: (key: APIKey) => void }) { const accounts = useProviderOptions(), [name, setName] = useState(''), [account, setAccount] = useState(''), [days, setDays] = useState(0), create = useAction(actions.createKey, ['keys']); return <Modal title="签发 API Key" onClose={onClose}><QueryState query={accounts}><form className="space-y-5" onSubmit={e => { e.preventDefault(); create.mutate({ name, account_id: Number(account), valid_seconds: days * 86400 }, { onSuccess: onCreated }) }}><Field label="名称"><Input required maxLength={64} value={name} onChange={e => setName(e.target.value)} placeholder="例如 Claude Code" /></Field><Field label="绑定账号"><AppSelect required value={account} onValueChange={setAccount}><SelectItem value="">请选择账号</SelectItem>{accounts.data?.items.filter(a => a.enabled).map(a => <SelectItem key={a.id} value={String(a.id)}>{a.name} · {a.provider}</SelectItem>)}</AppSelect></Field><Field label="有效期（天）" hint="0 表示长期有效"><Input required type="number" min={0} max={36500} step={1} value={days} onChange={e => setDays(Number(e.target.value))} /></Field><ErrorMessage error={create.error} /><div className="flex justify-end"><Submit pending={create.isPending}>签发 Key</Submit></div></form></QueryState></Modal> }

export function KeyDetails({ value, onClose }: { value: APIKey; provider?: ProviderOption; onClose: () => void }) { return <Modal title={`API Key 详情 · ${value.name}`} onClose={onClose}><div className="space-y-4"><ReadonlyField label="请求地址" value={publicBaseURL(location.href)} mono /><ReadonlyField label="API Key" value={value.key} mono /><Alert><CCSwitchIcon /><AlertTitle>使用 CC Switch 快速配置环境</AlertTitle><AlertDescription>在列表中点击该 Key 所在行的<CCSwitchIcon className="mx-1 inline-block size-3.5 align-[-3px]" />图标，选择对应客户端（Claude Code / Claude Desktop / Codex / Grok Build），即可自动写入上面的请求地址、API Key 与模型映射，无需手动配置环境变量。</AlertDescription></Alert></div></Modal> }

const defaultConfig = (client: CCSwitchClient, fallbackName: string): CCSwitchClientConfig => ({ supplier_name: fallbackName, remark: '', ...(client === 'grok_build' || client === 'codex' ? { default_model: '' } : { models: Object.fromEntries((client === 'claude_code' ? ['sonnet', 'opus', 'fable', 'haiku', 'subagent', 'fallback'] : ['sonnet', 'opus', 'fable', 'haiku']).map(k => [k, { model: '', supports_1m: false }])) }) })
function ModelSelect({ label, value, options, disabled, onChange }: { label: string; value: string; options: string[]; disabled?: boolean; onChange: (value: string) => void }) { return <Field label={label}><AppSelect value={value} disabled={disabled} onValueChange={onChange}><SelectItem value="">请选择模型</SelectItem>{options.map(model => <SelectItem key={model} value={model}>{model}</SelectItem>)}</AppSelect></Field> }

function CCSwitchExport({ value, client, keyID, onClose }: { value: APIKey; client: CCSwitchClient; keyID: number; onClose: () => void }) {
  const configQuery = useKeyConfig(keyID, client), modelsQuery = useProviderModels(value.account_id), save = useAction(actions.saveKeyConfig), [config, setConfig] = useState<CCSwitchClientConfig>(defaultConfig(client, value.name)), [error, setError] = useState<Error | null>(null)
  useEffect(() => { const saved = configQuery.data; const defaults = defaultConfig(client, value.name); setConfig({ ...defaults, ...saved, supplier_name: saved?.supplier_name || defaults.supplier_name, models: { ...defaults.models, ...saved?.models } }) }, [configQuery.data, client, value.name])
  const options = modelsQuery.data?.models.map(m => m.id) || [], model = (slot: string) => config.models?.[slot]?.model || ''
  const setModel = (slot: string, value: string) => setConfig(c => ({ ...c, models: { ...c.models, [slot]: { ...(c.models?.[slot] || { supports_1m: false }), model: value } } }))
  async function exportConfig() { setError(null); try { await save.mutateAsync({ id: keyID, client, config }); const imported = ccSwitchImportForClient({ pageURL: location.href, client, name: value.name, apiKey: value.key, config }); if (!imported) throw new Error('无法生成 CC Switch 配置'); location.href = imported.href } catch (e) { setError(e instanceof Error ? e : new Error('保存配置失败')) } }
  const slots = client === 'claude_code' ? ['sonnet', 'opus', 'fable', 'haiku', 'subagent', 'fallback'] : ['sonnet', 'opus', 'fable', 'haiku']
  const endpoint = ccSwitchEndpoint(publicBaseURL(location.href), client === 'claude_code' || client === 'claude_desktop' ? 'claude' : client === 'codex' ? 'codex' : 'grok')
  return <Modal title={`导出到 ${ccSwitchClientLabel[client]}`} onClose={onClose} wide><div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><CopyField label="请求地址" value={endpoint} mono /><CopyField label="API Key" value={value.key} mono /></div><Field label="名称"><Input value={config.supplier_name} onChange={e => setConfig(c => ({ ...c, supplier_name: e.target.value }))} /></Field><Field label="备注"><Input value={config.remark} onChange={e => setConfig(c => ({ ...c, remark: e.target.value }))} /></Field>{(client === 'codex' || client === 'grok_build') && <ModelSelect label="默认模型" value={config.default_model || ''} options={options} disabled={modelsQuery.isPending || !options.length} onChange={v => setConfig(c => ({ ...c, default_model: v }))} />}{client !== 'codex' && client !== 'grok_build' && slots.map(slot => <div key={slot} className="grid gap-3 sm:grid-cols-[1fr_180px_auto] sm:items-end"><ModelSelect label={{ fallback: '兜底模型', subagent: 'Subagent' }[slot] || slot[0].toUpperCase() + slot.slice(1)} value={model(slot)} options={options} disabled={modelsQuery.isPending || !options.length} onChange={v => setModel(slot, v)} /><label className="flex h-10 items-center gap-2 text-sm text-muted-foreground"><input type="checkbox" checked={config.models?.[slot]?.supports_1m || false} onChange={e => setConfig(c => ({ ...c, models: { ...c.models, [slot]: { ...(c.models?.[slot] || { model: '' }), supports_1m: e.target.checked } } }))} />声明支持 1M</label></div>)}{modelsQuery.error && <ErrorMessage error={modelsQuery.error} />}{configQuery.error && <ErrorMessage error={configQuery.error} />}{error && <ErrorMessage error={error} />}<div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose}>取消</Button><Button disabled={save.isPending || modelsQuery.isPending} onClick={exportConfig}>{save.isPending ? '保存中…' : 'CC Switch'}</Button></div></div></Modal>
}
