(function(){
      'use strict';
      var token=sessionStorage.getItem('unisub_admin_token')||'';
      var accounts=[];var usage={};var selectedProvider='codex';var selectedCode='curl';
      var names={overview:'总览',accounts:'账号管理',integration:'服务器集成',settings:'安全设置'};
      function $(id){return document.getElementById(id)}
      function escapeHTML(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
      function formatNumber(value){return new Intl.NumberFormat('zh-CN',{notation:Number(value)>=10000?'compact':'standard',maximumFractionDigits:1}).format(Number(value)||0)}
      function formatTime(value){if(!value)return '尚未使用';var d=new Date(value);return isNaN(d)?'—':d.toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
      function toast(message,error){var el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;$('toastStack').appendChild(el);setTimeout(function(){el.remove()},3200)}
      async function request(path,options){options=options||{};options.headers=Object.assign({},options.headers||{},{Authorization:'Bearer '+token,'Content-Type':'application/json'});var response=await fetch(path,options);if(response.status===204)return null;var body={};try{body=await response.json()}catch(e){}if(response.status===401){logout();throw new Error('会话已过期，请重新登录')}if(!response.ok)throw new Error(body.error&&body.error.message||response.statusText);return body}
      function logout(){token='';sessionStorage.removeItem('unisub_admin_token');$('appView').hidden=true;$('loginView').hidden=false;$('password').value=''}
      async function login(event){event.preventDefault();var button=$('loginButton');button.disabled=true;$('loginError').textContent='';try{var response=await fetch('/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});var body=await response.json();if(!response.ok)throw new Error(body.error&&body.error.message||'登录失败');token=body.token;sessionStorage.setItem('unisub_admin_token',token);showApp()}catch(e){$('loginError').textContent=e.message}finally{button.disabled=false}}
      function showApp(){$('loginView').hidden=true;$('appView').hidden=false;$('serverHost').textContent=location.host;loadData()}
      function navigate(page){document.querySelectorAll('.page').forEach(function(el){el.hidden=el.id!=='page-'+page});document.querySelectorAll('.nav button').forEach(function(el){el.classList.toggle('active',el.dataset.page===page)});$('crumbText').textContent=names[page];if(page==='integration')renderIntegrations()}
      async function loadData(){try{var result=await request('/admin/accounts');accounts=result.data||[];var pairs=await Promise.all(accounts.map(async function(a){try{return [a.id,await request('/admin/accounts/'+a.id+'/usage')]}catch(e){return [a.id,null]}}));usage={};pairs.forEach(function(pair){if(pair[1])usage[pair[0]]=pair[1]});renderOverview();renderAccountUsage();renderAccounts()}catch(e){toast(e.message,true)}}
      function totals(){var out={requests:0,input:0,output:0};Object.keys(usage).forEach(function(id){var local=usage[id]&&usage[id].local_usage||{};out.requests+=Number(local.requests_24h)||0;out.input+=Number(local.input_tokens_24h)||0;out.output+=Number(local.output_tokens_24h)||0});return out}
      function providerIcon(p){return '<span class="provider-logo '+escapeHTML(p)+'">'+({claude:'C',codex:'O',grok:'G'}[p]||'?')+'</span>'}
      function renderOverview(){var t=totals();$('statAccounts').textContent=formatNumber(accounts.length);$('statEnabled').textContent=accounts.filter(function(a){return a.enabled}).length+' 个已启用';$('statRequests').textContent=formatNumber(t.requests);$('statInput').textContent=formatNumber(t.input);$('statOutput').textContent=formatNumber(t.output);var counts={claude:0,codex:0,grok:0};accounts.forEach(function(a){counts[a.provider]=(counts[a.provider]||0)+1});var max=Math.max(1,counts.claude,counts.codex,counts.grok);$('providerBars').innerHTML=['claude','codex','grok'].map(function(p){return '<div class="provider-row"><div class="provider-name">'+providerIcon(p)+p.charAt(0).toUpperCase()+p.slice(1)+'</div><div class="bar"><i style="width:'+Math.round(counts[p]/max*100)+'%"></i></div><div class="provider-count">'+counts[p]+'</div></div>'}).join('');var recent=accounts.slice().sort(function(a,b){return new Date(b.last_used_at||b.created_at)-new Date(a.last_used_at||a.created_at)}).slice(0,4);$('recentActivity').innerHTML=recent.length?recent.map(function(a){return '<div class="activity-item"><span class="dot" style="margin-top:7px;background:'+(a.enabled?'var(--green)':'#69768a')+'"></span><div><p>'+escapeHTML(a.name)+'</p><small>'+escapeHTML(a.provider)+' · '+formatTime(a.last_used_at)+'</small></div><span class="badge '+(a.enabled?'ok':'off')+'">'+(a.enabled?'已启用':'已停用')+'</span></div>'}).join(''):'<div class="empty">还没有账号，先接入一个上游订阅吧。</div>'}
      function renderAccountUsage(){if(!accounts.length){$('accountUsageTable').innerHTML='<div class="empty">暂无账号使用量数据。</div>';return}var rows=accounts.slice().sort(function(a,b){var au=usage[a.id]&&usage[a.id].local_usage||{};var bu=usage[b.id]&&usage[b.id].local_usage||{};return (Number(bu.requests_24h)||0)-(Number(au.requests_24h)||0)});$('accountUsageTable').innerHTML='<table><thead><tr><th>账号</th><th>平台</th><th>状态</th><th>24h 请求</th><th>输入 Token</th><th>输出 Token</th><th>最后使用</th></tr></thead><tbody>'+rows.map(function(a){var available=!!usage[a.id];var u=available&&usage[a.id].local_usage||{};var metric=function(value){return available?formatNumber(value):'—'};return '<tr><td><div class="account-name">'+escapeHTML(a.name)+'</div><div class="subtle">ID '+a.id+'</div></td><td><div class="provider-name">'+providerIcon(a.provider)+escapeHTML(a.provider)+'</div></td><td><span class="badge '+(a.enabled?'ok':'off')+'">'+(a.enabled?'已启用':'已停用')+'</span></td><td>'+metric(u.requests_24h)+'</td><td>'+metric(u.input_tokens_24h)+'</td><td>'+metric(u.output_tokens_24h)+'</td><td class="subtle">'+formatTime(a.last_used_at)+'</td></tr>'}).join('')+'</tbody></table>'}
      function renderAccounts(){var query=$('accountSearch').value.trim().toLowerCase();var provider=$('providerFilter').value;var filtered=accounts.filter(function(a){return(!provider||a.provider===provider)&&(!query||(a.name+' '+a.provider+' '+a.api_key_prefix).toLowerCase().includes(query))});if(!filtered.length){$('accountTable').innerHTML='<div class="empty">没有匹配的账号。</div>';return}$('accountTable').innerHTML='<table><thead><tr><th>账号</th><th>平台</th><th>状态</th><th>API Key</th><th>24h 请求</th><th>最后使用</th><th style="text-align:right">操作</th></tr></thead><tbody>'+filtered.map(function(a){var u=usage[a.id]&&usage[a.id].local_usage||{};return '<tr><td><div class="account-name">'+escapeHTML(a.name)+'</div><div class="subtle">ID '+a.id+' · '+escapeHTML(a.auth_type)+(a.proxy_configured?' · 已配置代理':'')+(a.concurrency_queue_timeout_seconds?' · 队列 '+a.concurrency_queue_timeout_seconds+'s':' · 队列继承全局')+'</div></td><td><div class="provider-name">'+providerIcon(a.provider)+escapeHTML(a.provider)+'</div></td><td><span class="badge '+(a.enabled?'ok':'off')+'"><span class="dot" style="background:'+(a.enabled?'var(--green)':'#748196')+'"></span>'+(a.enabled?'已启用':'已停用')+'</span></td><td class="key">'+escapeHTML(a.api_key_prefix)+'…</td><td>'+formatNumber(u.requests_24h)+'</td><td class="subtle">'+formatTime(a.last_used_at)+'</td><td><div class="actions"><button title="'+(a.enabled?'停用':'启用')+'" data-action="toggle" data-id="'+a.id+'">'+(a.enabled?'⏸':'▶')+'</button><button title="设置并发队列等待" data-action="queue" data-id="'+a.id+'">◷</button><button title="设置代理" data-action="proxy" data-id="'+a.id+'">◎</button><button title="重置 API Key" data-action="reset" data-id="'+a.id+'">↻</button><button title="删除" data-action="delete" data-id="'+a.id+'" style="color:#ff8796">✕</button></div></td></tr>'}).join('')+'</tbody></table>'}
      function openAccountModal(){$('accountForm').reset();$('concurrencyLimit').value='1';$('concurrencyQueueTimeoutSeconds').value='0';$('credentials').value='';updateCredentialHint();$('accountModal').hidden=false;$('accountName').focus()}
      function closeAccountModal(){$('accountModal').hidden=true}
      function updateCredentialHint(){var p=$('accountProvider').value;var auth=$('authType').value;if(auth==='api_key'){$('credentials').placeholder='{"api_key":"..."}';$('credentialHint').textContent='填入上游平台 API Key。'}else if(p==='codex'){$('credentials').placeholder='{"access_token":"...","refresh_token":"...","chatgpt_account_id":"..."}';$('credentialHint').textContent='Codex OAuth 需要 access_token 和 chatgpt_account_id。'}else{$('credentials').placeholder='{"access_token":"...","refresh_token":"..."}';$('credentialHint').textContent='凭据以明文保存，管理 API 不会回显。'}}
      async function createAccount(event){event.preventDefault();var button=$('createButton');button.disabled=true;try{var credentials=JSON.parse($('credentials').value);var payload={name:$('accountName').value.trim(),provider:$('accountProvider').value,auth_type:$('authType').value,credentials:credentials,concurrency_limit:Number($('concurrencyLimit').value)||1,concurrency_queue_timeout_seconds:Number($('concurrencyQueueTimeoutSeconds').value)||0};if($('proxyURL').value.trim())payload.proxy_url=$('proxyURL').value.trim();if($('rpmLimit').value)payload.rpm_limit=Number($('rpmLimit').value);if($('tokenExpiresAt').value)payload.token_expires_at=new Date($('tokenExpiresAt').value).toISOString();var result=await request('/admin/accounts',{method:'POST',body:JSON.stringify(payload)});closeAccountModal();showKey(result.api_key,'账号创建成功');await loadData()}catch(e){toast(e.message,true)}finally{button.disabled=false}}
      function showKey(key,title){$('keyTitle').textContent=title;$('newAPIKey').value=key;$('keyModal').hidden=false}
      async function copyText(text){try{await navigator.clipboard.writeText(text);toast('已复制到剪贴板')}catch(e){var input=document.createElement('textarea');input.value=text;document.body.appendChild(input);input.select();document.execCommand('copy');input.remove();toast('已复制到剪贴板')}}
      async function accountAction(event){var button=event.target.closest('[data-action]');if(!button)return;var id=Number(button.dataset.id);var account=accounts.find(function(a){return a.id===id});if(!account)return;var action=button.dataset.action;if(action==='toggle'){try{await request('/admin/accounts/'+id+'/'+(account.enabled?'disable':'enable'),{method:'POST'});toast(account.enabled?'账号已停用':'账号已启用');await loadData()}catch(e){toast(e.message,true)}}if(action==='queue'){var wait=prompt('并发满额后的最大等待时间（秒）。0 表示继承环境变量缺省值，内置缺省为 180 秒。',String(account.concurrency_queue_timeout_seconds||0));if(wait===null)return;var waitSeconds=Number(wait);if(!Number.isInteger(waitSeconds)||waitSeconds<0||waitSeconds>300){toast('等待时间必须是 0 到 300 之间的整数',true);return}try{await request('/admin/accounts/'+id+'/concurrency-queue',{method:'PUT',body:JSON.stringify({concurrency_queue_timeout_seconds:waitSeconds})});toast('并发队列等待时间已更新');await loadData()}catch(e){toast(e.message,true)}}if(action==='proxy'){var value=prompt('输入 HTTP 或 SOCKS5 代理地址。留空会清除当前代理。\n例如：http://user:pass@127.0.0.1:8080', '');if(value===null)return;if(value.trim()===''&&account.proxy_configured&&!confirm('确定清除 '+account.name+' 的代理？'))return;try{await request('/admin/accounts/'+id+'/proxy',{method:'PUT',body:JSON.stringify({proxy_url:value.trim()})});toast(value.trim()?'账号代理已更新':'账号代理已清除');await loadData()}catch(e){toast(e.message,true)}}if(action==='reset'){if(!confirm('确定重置 '+account.name+' 的 API Key？旧 Key 将立即失效。'))return;try{var result=await request('/admin/accounts/'+id+'/api-key/reset',{method:'POST'});showKey(result.api_key,'API Key 已重置');await loadData()}catch(e){toast(e.message,true)}}if(action==='delete'){if(!confirm('确定删除 '+account.name+' ？其 API Key 和用量记录也将被删除。'))return;try{await request('/admin/accounts/'+id,{method:'DELETE'});toast('账号已删除');await loadData()}catch(e){toast(e.message,true)}}}
      function integrationData(){var base=location.origin;return[{id:'claude',name:'Claude',desc:'Anthropic Messages 与 Count Tokens 原生透传。',url:base+'/claude/v1'},{id:'codex',name:'Codex',desc:'OpenAI Responses 协议，支持 SSE 实时流。',url:base+'/codex/v1'},{id:'grok',name:'Grok',desc:'xAI Responses 协议原生透传。',url:base+'/grok/v1'}]}
      function renderIntegrations(){$('integrationCards').innerHTML=integrationData().map(function(item){return '<div class="card integration-card '+(item.id===selectedProvider?'selected':'')+'" data-provider="'+item.id+'"><h3>'+providerIcon(item.id)+item.name+'</h3><p>'+item.desc+'</p><div class="endpoint">'+escapeHTML(item.url)+'</div><div class="copy-row"><button class="btn" data-copy="'+escapeHTML(item.url)+'">复制 Base URL</button><button class="btn btn-primary" data-select="'+item.id+'">查看示例</button></div></div>'}).join('');renderCode()}
      function renderCode(){var base=location.origin;var route=selectedProvider==='claude'?'/v1/messages':'/v1/responses';var model=selectedProvider==='claude'?'claude-sonnet-4-5':selectedProvider==='codex'?'gpt-5':'grok-4';var url=base+'/'+selectedProvider+route;var body=selectedProvider==='claude'?'{\n  "model": "'+model+'",\n  "max_tokens": 512,\n  "messages": [{"role": "user", "content": "Hello"}]\n}':'{\n  "model": "'+model+'",\n  "input": "Hello",\n  "stream": true\n}';var samples={curl:'curl '+url+' \\\n  -H "Authorization: Bearer unisub_your_key" \\\n  -H "Content-Type: application/json" \\\n  -d \''+body.replace(/\n/g,' ')+'\'',python:'import requests\n\nresponse = requests.post(\n    "'+url+'",\n    headers={"Authorization": "Bearer unisub_your_key"},\n    json='+body.replace(/"/g,'\'').replace(/true/g,'True')+'\n)\nprint(response.json())',js:'const response = await fetch("'+url+'", {\n  method: "POST",\n  headers: {\n    "Authorization": "Bearer unisub_your_key",\n    "Content-Type": "application/json"\n  },\n  body: JSON.stringify('+body+' )\n});'};$('codeSample').textContent=samples[selectedCode]}
      async function changePassword(event){event.preventDefault();if($('newPassword').value!==$('confirmPassword').value){toast('两次输入的新密码不一致',true);return}try{await request('/admin/password',{method:'PUT',body:JSON.stringify({current_password:$('currentPassword').value,new_password:$('newPassword').value})});$('passwordForm').reset();toast('管理员密码已更新')}catch(e){toast(e.message,true)}}
      $('loginForm').addEventListener('submit',login);$('logoutButton').addEventListener('click',logout);$('refreshButton').addEventListener('click',loadData);$('pageAddButton').addEventListener('click',openAccountModal);$('accountForm').addEventListener('submit',createAccount);$('accountProvider').addEventListener('change',updateCredentialHint);$('authType').addEventListener('change',updateCredentialHint);$('accountSearch').addEventListener('input',renderAccounts);$('providerFilter').addEventListener('change',renderAccounts);$('accountTable').addEventListener('click',accountAction);$('passwordForm').addEventListener('submit',changePassword);$('copyKeyButton').addEventListener('click',function(){copyText($('newAPIKey').value)});
      document.querySelectorAll('.nav button').forEach(function(el){el.addEventListener('click',function(){navigate(el.dataset.page)})});document.querySelectorAll('[data-close]').forEach(function(el){el.addEventListener('click',closeAccountModal)});document.querySelectorAll('[data-key-close]').forEach(function(el){el.addEventListener('click',function(){$('keyModal').hidden=true;$('newAPIKey').value=''})});$('integrationCards').addEventListener('click',function(e){var copy=e.target.closest('[data-copy]');if(copy)copyText(copy.dataset.copy);var select=e.target.closest('[data-select]');if(select){selectedProvider=select.dataset.select;renderIntegrations()}});document.querySelectorAll('[data-code]').forEach(function(el){el.addEventListener('click',function(){selectedCode=el.dataset.code;document.querySelectorAll('[data-code]').forEach(function(x){x.classList.toggle('active',x===el)});renderCode()})});
      if(token)showApp();
    })();
