(function(){
      'use strict';
      var token=sessionStorage.getItem('unisub_admin_token')||'';
      var accounts=[];var keys=[];var users=[];var usage={};var currentUser=null;
      var grokOAuthFlowID='';var grokOAuthTimer=0;var editingAccountID=0;var editingKeyID=0;var plaintextKeys={};var pendingCCSwitchKey=null;
      var currentPage='personal';var logs=[];var logTotal=0;var logLimit=50;var logOffset=0;var logSearchTimer=0;var logCopyTexts=[];var personalRecentLogs=[];var landingResolved=false;
      var names={personal:'个人总览',overview:'系统总览',accounts:'账号管理',keys:'API Key',logs:'调用记录',users:'用户管理',security:'安全设置'};
      function $(id){return document.getElementById(id)}
      function escapeHTML(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
      function formatNumber(value){return new Intl.NumberFormat('zh-CN',{notation:Number(value)>=10000?'compact':'standard',maximumFractionDigits:1}).format(Number(value)||0)}
      function formatTime(value){if(!value)return '尚未使用';var d=new Date(value);return isNaN(d)?'—':d.toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
      function pad2(n){return String(n).padStart(2,'0')}
      function formatDuration(ms){ms=Number(ms)||0;if(ms<0)ms=0;var seconds=ms/1000;if(seconds<10)return seconds.toFixed(1)+' 秒';if(seconds<60)return Math.min(59,Math.round(seconds))+' 秒';var totalSec=Math.round(seconds);var min=Math.floor(totalSec/60);var sec=totalSec%60;return sec?min+' 分 '+sec+' 秒':min+' 分钟'}
      function formatDateTime(value){if(!value)return'—';var d=new Date(value);if(isNaN(d))return'—';return d.getFullYear()+'-'+pad2(d.getMonth()+1)+'-'+pad2(d.getDate())+' '+pad2(d.getHours())+':'+pad2(d.getMinutes())+':'+pad2(d.getSeconds())}
      function toast(message,error){var el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;$('toastStack').appendChild(el);setTimeout(function(){el.remove()},3200)}
      async function request(path,options){options=options||{};options.headers=Object.assign({},options.headers||{},{Authorization:'Bearer '+token,'Content-Type':'application/json'});var response=await fetch(path,options);if(response.status===204)return null;var body={};try{body=await response.json()}catch(e){}if(response.status===401){logout();throw new Error('会话已过期，请重新登录')}if(!response.ok)throw new Error(body.error&&body.error.message||response.statusText);return body}
      function logout(){token='';currentUser=null;landingResolved=false;sessionStorage.removeItem('unisub_admin_token');$('appView').hidden=true;$('loginView').hidden=false;$('password').value=''}
      async function login(event){event.preventDefault();var button=$('loginButton');button.disabled=true;$('loginError').textContent='';try{var response=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});var body=await response.json();if(!response.ok)throw new Error(body.error&&body.error.message||'登录失败');token=body.token;sessionStorage.setItem('unisub_admin_token',token);showApp()}catch(e){$('loginError').textContent=e.message}finally{button.disabled=false}}
      function showApp(){$('loginView').hidden=true;$('appView').hidden=false;$('serverHost').textContent=location.host;loadData()}
      function navigate(page){if((page==='overview'||page==='accounts'||page==='users')&&!isAdmin())page='personal';currentPage=page;document.querySelectorAll('.page').forEach(function(el){el.hidden=el.id!=='page-'+page});document.querySelectorAll('.nav button').forEach(function(el){el.classList.toggle('active',el.dataset.page===page)});$('crumbText').textContent=names[page];if(page==='personal')renderPersonalOverview();if(page==='overview')renderOverview();if(page==='keys')renderAPIKeys();if(page==='users')renderUsers();if(page==='logs'){fillLogFilters();loadLogs()}}
      function isAdmin(){return currentUser&&currentUser.role==='admin'}
      async function loadData(){try{var me=await request('/api/me');currentUser=me.user||null;if(currentUser){$('serverHost').textContent=currentUser.username+' · '+location.host;$('personalUserBadge').innerHTML='<span class="dot"></span> '+escapeHTML(currentUser.username)}var admin=isAdmin();$('overviewNav').hidden=!admin;$('accountsNav').hidden=!admin;$('usersNav').hidden=!admin;if(!landingResolved){landingResolved=true;navigate(admin?'overview':'personal')}else if(!admin&&(currentPage==='overview'||currentPage==='accounts'||currentPage==='users'))navigate('personal');var result=await request('/api/accounts');accounts=result.data||[];var keyResult=await request('/api/api-keys');keys=keyResult.data||[];users=[];if(admin){var userResult=await request('/api/users');users=userResult.data||[]}var pairs=await Promise.all(accounts.map(async function(a){try{return [a.id,await request('/api/accounts/'+a.id+'/usage')]}catch(e){return [a.id,null]}}));usage={};pairs.forEach(function(pair){if(pair[1])usage[pair[0]]=pair[1]});try{var recent=await request('/api/request-logs?limit=8&offset=0');personalRecentLogs=recent.data||[]}catch(e){personalRecentLogs=[]}renderPersonalOverview();renderOverview();renderAccounts();renderAPIKeys();renderUsers();if(currentPage==='logs')fillLogFilters()}catch(e){toast(e.message,true)}}
      function totals(){var out={requests:0,input:0,output:0};Object.keys(usage).forEach(function(id){var local=usage[id]&&usage[id].local_usage||{};out.requests+=Number(local.requests_24h)||0;out.input+=Number(local.input_tokens_24h)||0;out.output+=Number(local.output_tokens_24h)||0});return out}
      function personalKeyAccountIDs(){var set={};keys.forEach(function(k){set[k.account_id]=true});return Object.keys(set).map(Number)}
      function personalTotals(){var out={requests:0,input:0,output:0};personalKeyAccountIDs().forEach(function(id){var local=usage[id]&&usage[id].local_usage||{};out.requests+=Number(local.requests_24h)||0;out.input+=Number(local.input_tokens_24h)||0;out.output+=Number(local.output_tokens_24h)||0});return out}
      function providerIcon(p){return '<span class="provider-logo '+escapeHTML(p)+'">'+({claude:'C',codex:'O',grok:'G'}[p]||'?')+'</span>'}
      function renderOverview(){var t=totals();$('statAccounts').textContent=formatNumber(accounts.length);$('statEnabled').textContent=accounts.filter(function(a){return a.enabled}).length+' 个已启用';$('statRequests').textContent=formatNumber(t.requests);$('statInput').textContent=formatNumber(t.input);$('statOutput').textContent=formatNumber(t.output);var counts={claude:0,codex:0,grok:0};accounts.forEach(function(a){counts[a.provider]=(counts[a.provider]||0)+1});var max=Math.max(1,counts.claude,counts.codex,counts.grok);$('providerBars').innerHTML=['claude','codex','grok'].map(function(p){return '<div class="provider-row"><div class="provider-name">'+providerIcon(p)+p.charAt(0).toUpperCase()+p.slice(1)+'</div><div class="bar"><i style="width:'+Math.round(counts[p]/max*100)+'%"></i></div><div class="provider-count">'+counts[p]+'</div></div>'}).join('');var recent=accounts.slice().sort(function(a,b){return new Date(b.last_used_at||b.created_at)-new Date(a.last_used_at||a.created_at)}).slice(0,4);$('recentActivity').innerHTML=recent.length?recent.map(function(a){return '<div class="activity-item"><span class="dot" style="margin-top:7px;background:'+(a.enabled?'var(--green)':'#69768a')+'"></span><div><p>'+escapeHTML(a.name)+'</p><small>'+escapeHTML(a.provider)+' · '+formatTime(a.last_used_at)+'</small></div><span class="badge '+(a.enabled?'ok':'off')+'">'+(a.enabled?'已启用':'已停用')+'</span></div>'}).join(''):'<div class="empty">还没有账号，先接入一个上游订阅吧。</div>'}
      function renderPersonalOverview(){var mine=keys;var t=personalTotals();$('personalStatKeys').textContent=formatNumber(mine.length);$('personalStatKeysEnabled').textContent=mine.filter(function(k){return k.enabled}).length+' 个已启用';$('personalStatRequests').textContent=formatNumber(t.requests);$('personalStatInput').textContent=formatNumber(t.input);$('personalStatOutput').textContent=formatNumber(t.output);var counts={claude:0,codex:0,grok:0};mine.forEach(function(k){counts[k.provider]=(counts[k.provider]||0)+1});var max=Math.max(1,counts.claude,counts.codex,counts.grok);$('personalKeyBars').innerHTML=mine.length?['claude','codex','grok'].map(function(p){return '<div class="provider-row"><div class="provider-name">'+providerIcon(p)+p.charAt(0).toUpperCase()+p.slice(1)+'</div><div class="bar"><i style="width:'+Math.round(counts[p]/max*100)+'%"></i></div><div class="provider-count">'+counts[p]+'</div></div>'}).join(''):'<div class="empty">还没有 API Key。先到 API Key 页面签发。</div>';var recent=personalRecentLogs.slice(0,5);$('personalRecentCalls').innerHTML=recent.length?recent.map(function(log){var ok=log.status_code>=200&&log.status_code<300;return '<div class="activity-item"><span class="dot" style="margin-top:7px;background:'+(ok?'var(--green)':(log.status_code===429||log.status_code===499?'var(--orange)':'var(--red)'))+'"></span><div><p>'+escapeHTML(log.model||log.provider||log.path||'调用')+'</p><small>'+escapeHTML(formatDateTime(log.started_at))+' · '+escapeHTML(log.account_name||'未绑定')+' · '+formatDuration(log.duration_ms)+'</small></div><span class="badge '+statusClass(log.status_code)+'">'+log.status_code+'</span></div>'}).join(''):'<div class="empty">暂无调用记录。</div>'}
      function quotaWindowName(name){return({five_hour:'5 小时',five_hours:'5 小时',daily:'每日',seven_day:'7 天',weekly:'每周',monthly:'每月'}[String(name||'').toLowerCase()]||String(name||'Usage'))}
      function usagePercent(value){if(!value||typeof value!=='object')return null;var used=Number(value.used_percent);if(Number.isFinite(used))return Math.max(0,Math.min(100,used));var remaining=Number(value.remaining_percent);if(Number.isFinite(remaining))return Math.max(0,Math.min(100,100-remaining));var usedCount=value.used;if(usedCount==null)usedCount=value.used_count;if(usedCount==null)usedCount=value.used_tokens;var remainingCount=value.remaining;if(remainingCount==null)remainingCount=value.remaining_count;if(remainingCount==null)remainingCount=value.remaining_tokens;if(remainingCount==null)remainingCount=value.balance;var limit=value.limit;if(limit==null)limit=value.total;if(limit==null)limit=value.cap;if(usedCount==null&&remainingCount!=null&&limit!=null)usedCount=Number(limit)-Number(remainingCount);if(Number.isFinite(Number(usedCount))&&Number(limit)>0)return Math.max(0,Math.min(100,Number(usedCount)/Number(limit)*100));return null}
      function formatUsagePercent(percent){return percent.toFixed(1).replace(/\.0$/,'')+'%'}
      function quotaPercent(window){return usagePercent(window)}
      function quotaObjectLine(value,label){var percent=usagePercent(value);if(percent===null)return'';var detail=label+(value&&value.reset_at?' · '+formatTime(value.reset_at):'');return '<div class="quota-window"><b>'+escapeHTML(formatUsagePercent(percent))+'</b><small>'+escapeHTML(detail)+'</small></div>'}
      function creditBalanceLine(value,label){var percent=value!=null&&typeof value==='object'?usagePercent(value):null;if(percent===null)return'';return '<div class="quota-window"><b>'+escapeHTML(formatUsagePercent(percent))+'</b><small>'+escapeHTML(label)+'</small></div>'}
      function renderQuota(account){var q=usage[account.id];if(!q||q.status!=='available'){var detail=q&&q.error?String(q.error):'暂无上游 Usage';return '<div class="quota-unknown" title="'+escapeHTML(detail)+'"><span class="badge warn">未知</span><small>'+escapeHTML(detail)+'</small></div>'}var windows=Array.isArray(q.windows)?q.windows:[];var lines=windows.slice(0,2).map(function(window){var percent=quotaPercent(window);if(percent===null)return'';var detail=quotaWindowName(window.name)+(window.reset_at?' · '+formatTime(window.reset_at):'');return '<div class="quota-window"><b>'+escapeHTML(formatUsagePercent(percent))+'</b><small>'+escapeHTML(detail)+'</small></div>'}).filter(Boolean);if(!lines.length){var requestLine=quotaObjectLine(q.request_quota,'请求');var tokenLine=quotaObjectLine(q.token_quota,'Token');if(requestLine)lines.push(requestLine);if(tokenLine)lines.push(tokenLine)}var credits=q.credit_balance||{};var prepaidLine=creditBalanceLine(credits.prepaid,'Prepaid');var onDemandLine=creditBalanceLine(credits.on_demand,'On-demand');if(prepaidLine)lines.push(prepaidLine);if(onDemandLine)lines.push(onDemandLine);if(!lines.length)return '<div class="quota-unknown"><span class="badge warn">未知</span><small>上游未返回 Usage</small></div>';var tier=q.subscription_tier?'<div class="quota-tier">'+escapeHTML(q.subscription_tier)+'</div>':'';var checked=q.checked_at?'<div class="quota-checked">'+(q.stale?'数据可能已过期 · ':'查询于 ')+escapeHTML(formatTime(q.checked_at))+'</div>':'';var refreshError=q.error?'<div class="quota-checked" title="'+escapeHTML(q.error)+'">最近查询失败，保留上次数据</div>':'';return '<div class="quota-cell">'+tier+lines.join('')+checked+refreshError+'</div>'}
      function formatLocalTokens(local,available){if(!available)return'—';var input=Number(local.input_tokens_24h)||0;var output=Number(local.output_tokens_24h)||0;var cacheCreate=Number(local.cache_creation_tokens_24h)||0;var cacheRead=Number(local.cache_read_tokens_24h)||0;var total=local.total_tokens_24h!=null?Number(local.total_tokens_24h):(input+output);return'<div class="subtle">输入 '+escapeHTML(formatNumber(input))+' · 输出 '+escapeHTML(formatNumber(output))+'</div><div class="subtle">缓存创建 '+escapeHTML(formatNumber(cacheCreate))+' · 缓存读取 '+escapeHTML(formatNumber(cacheRead))+'</div><div class="subtle">总数 '+escapeHTML(formatNumber(total))+'</div>'}
      function renderAccounts(){var query=$('accountSearch').value.trim().toLowerCase();var provider=$('providerFilter').value;var filtered=accounts.filter(function(a){return(!provider||a.provider===provider)&&(!query||(a.name+' '+a.provider).toLowerCase().includes(query))});if(!filtered.length){$('accountTable').innerHTML='<div class="empty">'+(accounts.length?'没有匹配的账号。':'暂无账号。先接入一个上游订阅吧。')+'</div>';return}$('accountTable').innerHTML='<table><thead><tr><th>账号</th><th>平台</th><th>状态</th><th>Usage</th><th>24h 请求</th><th>Token</th><th style="text-align:right">操作</th></tr></thead><tbody>'+filtered.map(function(a){var available=!!usage[a.id];var u=available&&usage[a.id].local_usage||{};var metric=function(value){return available?formatNumber(value):'—'};return '<tr><td><div class="account-name">'+escapeHTML(a.name)+'</div><div class="subtle">ID '+a.id+' · '+escapeHTML(a.auth_type)+(a.proxy_configured?' · 已配置代理':'')+(a.concurrency_queue_timeout_seconds?' · 队列 '+a.concurrency_queue_timeout_seconds+'s':' · 队列继承全局')+'</div></td><td><div class="provider-name">'+providerIcon(a.provider)+escapeHTML(a.provider)+'</div></td><td><span class="badge '+(a.enabled?'ok':'off')+'"><span class="dot" style="background:'+(a.enabled?'var(--green)':'#748196')+'"></span>'+(a.enabled?'已启用':'已停用')+'</span></td><td>'+renderQuota(a)+'</td><td>'+metric(u.requests_24h)+'</td><td>'+formatLocalTokens(u,available)+'</td><td><div class="actions"><button class="btn" type="button" data-action="edit" data-id="'+a.id+'">编辑</button><button class="btn btn-danger" type="button" data-action="delete" data-id="'+a.id+'">删除</button></div></td></tr>'}).join('')+'</tbody></table>'}
      function setAccountModalMode(account){editingAccountID=account?account.id:0;var editing=!!editingAccountID;document.querySelectorAll('#accountForm .create-only').forEach(function(el){el.hidden=editing});document.querySelectorAll('#accountForm .edit-only').forEach(function(el){el.hidden=!editing});$('accountProvider').disabled=editing;$('authType').disabled=editing;$('accountModalTitle').textContent=editing?'编辑账号':'接入上游账号';$('deleteAccountButton').hidden=!editing;$('refreshUsageButton').hidden=!(editing&&account&&account.provider==='grok'&&account.auth_type==='oauth');$('clearProxyField').hidden=!(editing&&account&&account.proxy_configured);$('clearProxy').checked=false;$('proxyHint').textContent=editing&&account&&account.proxy_configured?'已配置代理。留空保持不变，勾选下方选项可清除。':'代理地址以明文保存，管理 API 不会回显。';updateCredentialHint()}
      function openAccountModal(){$('accountForm').reset();$('concurrencyLimit').value='1';$('concurrencyQueueTimeoutSeconds').value='0';$('credentials').value='';$('accountEnabled').value='1';setAccountModalMode(null);$('accountModal').hidden=false;$('accountName').focus()}
      function prettyJSON(value){if(value==null||value==='')return'';if(typeof value==='string'){try{return JSON.stringify(JSON.parse(value),null,2)}catch(e){return value}}try{return JSON.stringify(value,null,2)}catch(e){return''}}
      async function openEditAccount(account){$('accountForm').reset();$('accountName').value=account.name;$('accountProvider').value=account.provider;$('authType').value=account.auth_type;$('accountEnabled').value=account.enabled?'1':'0';$('concurrencyLimit').value=String(account.concurrency_limit||1);$('concurrencyQueueTimeoutSeconds').value=String(account.concurrency_queue_timeout_seconds||0);$('proxyURL').value='';$('credentials').value='';setAccountModalMode(account);$('accountModal').hidden=false;$('accountName').focus();try{var detail=await request('/api/accounts/'+account.id);$('credentials').value=prettyJSON(detail.account&&detail.account.credentials)}catch(e){toast(e.message,true)}}
      function closeAccountModal(){editingAccountID=0;$('accountModal').hidden=true}
      function updateCredentialHint(){var editing=!!editingAccountID;var p=$('accountProvider').value;var auth=$('authType').value;var grokLogin=!editing&&p==='grok'&&auth==='oauth';$('credentials').required=!grokLogin;$('credentials').disabled=grokLogin;$('tokenExpiresAt').disabled=editing||grokLogin;if(editing){$('credentials').placeholder='{"access_token":"..."}';$('credentialHint').textContent='保存修改时会写入当前 JSON。';$('createButton').textContent='保存修改';return}if(grokLogin){$('credentials').placeholder='由 xAI OAuth 登录自动填写';$('credentialHint').textContent='提交后会显示 xAI 设备授权码，登录成功后自动保存并续期 Token。';$('createButton').textContent='登录并绑定 Grok'}else if(auth==='api_key'){$('credentials').placeholder='{"api_key":"..."}';$('credentialHint').textContent='填入上游平台 API Key。';$('createButton').textContent='创建账号'}else if(p==='codex'){$('credentials').placeholder='{"access_token":"...","refresh_token":"...","chatgpt_account_id":"..."}';$('credentialHint').textContent='Codex OAuth 需要 access_token 和 chatgpt_account_id。';$('createButton').textContent='创建账号'}else{$('credentials').placeholder='{"access_token":"...","refresh_token":"..."}';$('credentialHint').textContent='凭据以明文保存。';$('createButton').textContent='创建账号'}}
      function accountFormPayload(){var payload={name:$('accountName').value.trim(),concurrency_limit:Number($('concurrencyLimit').value)||1,concurrency_queue_timeout_seconds:Number($('concurrencyQueueTimeoutSeconds').value)||0};if($('proxyURL').value.trim())payload.proxy_url=$('proxyURL').value.trim();return payload}
      async function saveAccount(event){event.preventDefault();var button=$('createButton');button.disabled=true;try{if(editingAccountID){var account=accounts.find(function(item){return item.id===editingAccountID});var payload=accountFormPayload();payload.enabled=$('accountEnabled').value==='1';if($('clearProxy').checked)payload.proxy_url='';else if(!payload.proxy_url&&account&&account.proxy_configured)delete payload.proxy_url;try{payload.credentials=JSON.parse($('credentials').value)}catch(e){toast('凭据 JSON 无效',true);return}await request('/api/accounts/'+editingAccountID,{method:'PUT',body:JSON.stringify(payload)});closeAccountModal();toast('账号已更新');await loadData();return}var provider=$('accountProvider').value;var auth=$('authType').value;var payload=accountFormPayload();if(provider==='grok'&&auth==='oauth'){closeAccountModal();$('grokOAuthModal').hidden=false;$('grokOAuthCode').textContent='—';$('grokOAuthStatus').textContent='正在向 xAI 申请登录码…';$('grokOAuthOpen').href='#';var started=await request('/api/providers/grok/oauth/device/start',{method:'POST',body:JSON.stringify(payload)});grokOAuthFlowID=started.flow_id;$('grokOAuthCode').textContent=started.user_code;$('grokOAuthOpen').href=started.verification_uri_complete||started.verification_uri;$('grokOAuthStatus').textContent='请打开授权页面并输入上方代码，完成后本页会自动继续。';scheduleGrokOAuthPoll((Number(started.interval)||5)*1000);return}payload.provider=provider;payload.auth_type=auth;payload.credentials=JSON.parse($('credentials').value);if($('tokenExpiresAt').value)payload.token_expires_at=new Date($('tokenExpiresAt').value).toISOString();await request('/api/accounts',{method:'POST',body:JSON.stringify(payload)});closeAccountModal();toast('账号已创建，请到 API Key 页面签发调用密钥');await loadData()}catch(e){$('grokOAuthModal').hidden=true;toast(e.message,true)}finally{button.disabled=false}}
      function scheduleGrokOAuthPoll(delay){clearTimeout(grokOAuthTimer);if(!grokOAuthFlowID)return;grokOAuthTimer=setTimeout(pollGrokOAuth,Math.max(1000,delay||5000))}
      async function pollGrokOAuth(){if(!grokOAuthFlowID)return;try{var result=await request('/api/providers/grok/oauth/device/poll',{method:'POST',body:JSON.stringify({flow_id:grokOAuthFlowID})});if(result.status==='complete'){grokOAuthFlowID='';$('grokOAuthModal').hidden=true;toast('Grok 账号绑定成功，请到 API Key 页面签发调用密钥');await loadData();return}$('grokOAuthStatus').textContent='等待你在 xAI 页面确认授权…';scheduleGrokOAuthPoll((Number(result.retry_after)||5)*1000)}catch(e){grokOAuthFlowID='';$('grokOAuthModal').hidden=true;toast(e.message,true)}}
      function cancelGrokOAuth(){grokOAuthFlowID='';clearTimeout(grokOAuthTimer);$('grokOAuthModal').hidden=true}
      async function refreshData(){var button=$('refreshButton');button.disabled=true;try{if(currentPage==='logs'){await loadLogs();toast('调用记录已刷新');return}var targets=accounts.filter(function(a){return a.provider==='grok'&&a.auth_type==='oauth'});var results=await Promise.all(targets.map(async function(a){try{await request('/api/accounts/'+a.id+'/usage/refresh',{method:'POST'});return true}catch(e){return false}}));await loadData();if(targets.length){var success=results.filter(Boolean).length;toast(success===targets.length?'Grok Usage 已刷新':'已刷新 '+success+'/'+targets.length+' 个 Grok 账号',success!==targets.length)}else{toast('数据已刷新')}}finally{button.disabled=false}}
      function showKey(key,title,meta){$('keyTitle').textContent=title;$('newAPIKey').value=key;pendingCCSwitchKey=meta||null;if(meta&&meta.id)plaintextKeys[meta.id]=key;$('ccSwitchFromKeyModal').hidden=!meta;$('keyModal').hidden=false}
      async function copyText(text){try{await navigator.clipboard.writeText(text);toast('已复制到剪贴板')}catch(e){var input=document.createElement('textarea');input.value=text;document.body.appendChild(input);input.select();document.execCommand('copy');input.remove();toast('已复制到剪贴板')}}
      function editingAccount(){return accounts.find(function(a){return a.id===editingAccountID})}
      async function accountAction(event){var button=event.target.closest('[data-action]');if(!button)return;var id=Number(button.dataset.id);var account=accounts.find(function(a){return a.id===id});if(!account)return;if(button.dataset.action==='edit')openEditAccount(account);if(button.dataset.action==='delete')deleteAccount(account)}
      async function refreshEditingUsage(){var account=editingAccount();if(!account)return;try{await request('/api/accounts/'+account.id+'/usage/refresh',{method:'POST'});toast(account.name+' 的 Usage 已刷新');await loadData()}catch(e){toast(e.message,true)}}
      async function deleteAccount(account){if(!account||!confirm('确定删除 '+account.name+' ？其 API Key 和用量记录也将被删除。'))return;try{await request('/api/accounts/'+account.id,{method:'DELETE'});closeAccountModal();toast('账号已删除');await loadData()}catch(e){toast(e.message,true)}}
      async function deleteEditingAccount(){return deleteAccount(editingAccount())}
      function statusClass(code){if(code>=200&&code<300)return'ok';if(code===429||code===499)return'warn';if(code>=400)return'off';return''}
      function formatTokens(log){if(log.input_tokens==null&&log.output_tokens==null&&log.cache_read_tokens==null&&log.cache_creation_tokens==null&&log.total_tokens==null)return'—';var total=log.total_tokens!=null?log.total_tokens:(Number(log.input_tokens)||0)+(Number(log.output_tokens)||0);return'<div class="subtle">输入 '+escapeHTML(formatNumber(log.input_tokens||0))+' · 输出 '+escapeHTML(formatNumber(log.output_tokens||0))+'</div><div class="subtle">缓存读 '+escapeHTML(formatNumber(log.cache_read_tokens||0))+' · 缓存写 '+escapeHTML(formatNumber(log.cache_creation_tokens||0))+'</div><div class="subtle">合计 '+escapeHTML(formatNumber(total))+'</div>'}
      function fillLogFilters(){var admin=isAdmin();$('logAccountFilter').hidden=!admin;if(!admin){$('logAccountFilter').value='';return}var selected=$('logAccountFilter').value;var options='<option value="">全部账号</option>'+accounts.map(function(a){return '<option value="'+a.id+'">'+escapeHTML(a.name)+' · '+escapeHTML(a.provider)+'</option>'}).join('');$('logAccountFilter').innerHTML=options;if(selected&&Array.prototype.some.call($('logAccountFilter').options,function(o){return o.value===selected}))$('logAccountFilter').value=selected;else $('logAccountFilter').value=''}
      function logQueryParams(){var params=new URLSearchParams({limit:String(logLimit),offset:String(logOffset)});if(isAdmin()&&$('logAccountFilter').value)params.set('account_id',$('logAccountFilter').value);if($('logProviderFilter').value)params.set('provider',$('logProviderFilter').value);if($('logStatusFilter').value)params.set('status',$('logStatusFilter').value);if($('logSearch').value.trim())params.set('q',$('logSearch').value.trim());return params}
      async function loadLogs(){fillLogFilters();try{var result=await request('/api/request-logs?'+logQueryParams());logs=result.data||[];logTotal=Number(result.total)||0;logLimit=Number(result.limit)||logLimit;logOffset=Number(result.offset)||0;renderLogs()}catch(e){toast(e.message,true)}}
      function logKeyLabel(log){var name=String(log.api_key_name||'').trim();var prefix=String(log.api_key_prefix||'').trim();if(!name&&!prefix)return'';if(name&&prefix)return'Key '+name+' · '+prefix+'…';if(name)return'Key '+name;return'Key '+prefix+'…'}
      function renderLogs(){if(!logs.length){$('logTable').innerHTML='<div class="empty">暂无调用记录。转发请求后会出现在这里。</div>';$('logPager').innerHTML='';return}$('logTable').innerHTML='<table><thead><tr><th>ID</th><th>模型</th><th>账号</th><th>状态</th><th>Token</th></tr></thead><tbody>'+logs.map(function(log){var path=escapeHTML(log.path||'')+(log.query?'?'+escapeHTML(log.query):'');var account=escapeHTML(log.account_name||(log.account_id?'账号 '+log.account_id:'未绑定'));var keyLabel=logKeyLabel(log);return '<tr class="click-row" data-log-day="'+escapeHTML(log.day)+'" data-log-id="'+log.id+'"><td><div class="account-name">#'+log.id+' <span class="subtle">'+escapeHTML(formatDateTime(log.started_at))+'</span></div><div class="subtle">'+escapeHTML(log.client_ip||'')+(log.client_ip&&log.request_id?' · ':'')+escapeHTML(log.request_id||'')+'</div></td><td><div class="account-name">'+escapeHTML(log.model||log.provider||'—')+'</div><div class="subtle">'+escapeHTML(log.method)+' '+path+'</div></td><td><div class="account-name">'+account+'</div>'+(keyLabel?'<div class="subtle">'+escapeHTML(keyLabel)+'</div>':'')+'</td><td><span class="badge '+statusClass(log.status_code)+'">'+log.status_code+'</span> <span class="subtle">'+formatDuration(log.duration_ms)+'</span>'+(log.error_type?'<div class="subtle">'+escapeHTML(log.error_type)+'</div>':'')+'</td><td>'+formatTokens(log)+'</td></tr>'}).join('')+'</tbody></table>';var from=logTotal?logOffset+1:0;var to=Math.min(logOffset+logs.length,logTotal);$('logPager').innerHTML='<span>'+from+'-'+to+' / '+formatNumber(logTotal)+'</span><button class="btn" type="button" id="logPrev"'+(logOffset<=0?' disabled':'')+'>上一页</button><button class="btn" type="button" id="logNext"'+(logOffset+logLimit>=logTotal?' disabled':'')+'>下一页</button>'}
      function formatLogJSON(value){if(!value)return'';try{return JSON.stringify(JSON.parse(value),null,2)}catch(e){return String(value)}}
      function formatLogHeaders(value){if(!value)return'';try{var parsed=JSON.parse(value);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))return String(value);return Object.keys(parsed).map(function(key){var vals=parsed[key];if(!Array.isArray(vals))vals=[vals];return vals.map(function(item){return key+': '+item}).join('\n')}).filter(Boolean).join('\n')}catch(e){return String(value)}}
      function logCopyButton(text){var content=text||'';var idx=logCopyTexts.length;logCopyTexts.push(content);return '<button class="btn log-copy" type="button" data-copy-index="'+idx+'"'+(content?'':' disabled')+'>复制</button>'}
      function logBlock(title,hint,text){var content=text||'';return '<div class="field log-block"><div class="log-block-head"><button class="log-toggle" type="button" data-log-toggle aria-expanded="true"><span class="log-chevron" aria-hidden="true"></span><span>'+escapeHTML(title)+'</span></button>'+logCopyButton(content)+'</div>'+(hint?'<div class="subtle log-block-hint">'+hint+'</div>':'')+'<pre class="log-pre">'+escapeHTML(content||'—')+'</pre></div>'}
      function logMetaItem(label,value,copyable){var text=value||'';return '<div><small>'+escapeHTML(label)+'</small><div class="log-meta-value"><b>'+escapeHTML(text||'—')+'</b>'+(copyable&&text?logCopyButton(text):'')+'</div></div>'}
      async function openLog(day,id){try{var result=await request('/api/request-logs/'+encodeURIComponent(day)+'/'+id);var log=result.log||{};logCopyTexts=[];var requestLine=escapeHTML(log.method)+' '+escapeHTML(log.path||'')+(log.query?'?'+escapeHTML(log.query):'');$('logModalBody').innerHTML='<div class="log-meta">'+logMetaItem('日志 ID',(log.day||day)+' / #'+(log.id||id),true)+logMetaItem('账号',log.account_name||'',true)+logMetaItem('模型',log.model||'',true)+'<div><small>Token</small>'+formatTokens(log)+'</div>'+logMetaItem('来源 IP',log.client_ip||'',true)+logMetaItem('Request ID',log.request_id||'',true)+logMetaItem('错误',log.error_type||'',true)+'<div><small>耗时</small><b>'+formatDuration(log.duration_ms)+'</b></div></div>'+logBlock('Request Headers',requestLine,formatLogHeaders(log.request_headers))+logBlock('Request Body',log.request_truncated?'已截断':'',formatLogJSON(log.request_body)||log.request_body||'')+logBlock('Response Headers','HTTP '+log.status_code,formatLogHeaders(log.response_headers))+logBlock('Response Body',log.response_truncated?'已截断':'',formatLogJSON(log.response_body)||log.response_body||'');$('logModal').hidden=false}catch(e){toast(e.message,true)}}
      function logModalClick(event){var copy=event.target.closest('[data-copy-index]');if(copy){if(!copy.disabled)copyText(logCopyTexts[Number(copy.dataset.copyIndex)]||'');return}var head=event.target.closest('.log-block-head');if(!head)return;var block=head.closest('.log-block');if(!block)return;var collapsed=block.classList.toggle('collapsed');var toggle=block.querySelector('[data-log-toggle]');if(toggle)toggle.setAttribute('aria-expanded',collapsed?'false':'true')}
      function logTableClick(event){var row=event.target.closest('[data-log-day]');if(!row)return;openLog(row.dataset.logDay,row.dataset.logId)}
      function logPagerClick(event){if(event.target.id==='logPrev'&&logOffset>0){logOffset=Math.max(0,logOffset-logLimit);loadLogs()}if(event.target.id==='logNext'&&logOffset+logLimit<logTotal){logOffset+=logLimit;loadLogs()}}
      function resetLogOffsetAndLoad(){logOffset=0;loadLogs()}
      function fillAPIKeyAccountOptions(selected){var filter=$('keyAccountFilter').value;$('apiKeyAccount').innerHTML=accounts.map(function(a){return '<option value="'+a.id+'"'+(String(a.id)===String(selected)?' selected':'')+'>'+escapeHTML(a.name)+' · '+escapeHTML(a.provider)+'</option>'}).join('');$('keyAccountFilter').innerHTML='<option value="">全部账号</option>'+accounts.map(function(a){return '<option value="'+a.id+'">'+escapeHTML(a.name)+'</option>'}).join('');if(filter)$('keyAccountFilter').value=filter}
      function renderAPIKeys(){fillAPIKeyAccountOptions($('apiKeyAccount').value);var query=$('keySearch').value.trim().toLowerCase();var accountID=$('keyAccountFilter').value;var filtered=keys.filter(function(k){return(!accountID||String(k.account_id)===accountID)&&(!query||(k.name+' '+k.key_prefix+' '+k.account_name+' '+k.provider).toLowerCase().includes(query))});if(!filtered.length){$('keyTable').innerHTML='<div class="empty">暂无 API Key。先接入账号，再在这里签发。</div>';return}$('keyTable').innerHTML='<table><thead><tr><th>Key</th><th>账号</th><th>平台</th><th>状态</th><th>RPM</th><th>创建时间</th><th style="text-align:right">操作</th></tr></thead><tbody>'+filtered.map(function(k){return '<tr><td><div class="account-name">'+escapeHTML(k.name)+'</div><div class="key subtle">'+escapeHTML(k.key_prefix)+'…</div></td><td>'+escapeHTML(k.account_name)+'</td><td><div class="provider-name">'+providerIcon(k.provider)+escapeHTML(k.provider)+'</div></td><td><span class="badge '+(k.enabled?'ok':'off')+'">'+(k.enabled?'已启用':'已停用')+'</span></td><td>'+(k.rpm_limit==null?'—':formatNumber(k.rpm_limit))+'</td><td class="subtle">'+formatTime(k.created_at)+'</td><td><div class="actions"><button class="btn" type="button" data-key-action="ccswitch" data-id="'+k.id+'">CC Switch</button><button class="btn" type="button" data-key-action="edit" data-id="'+k.id+'">编辑</button></div></td></tr>'}).join('')+'</tbody></table>'}
      function closeAPIKeyForm(){editingKeyID=0;$('apiKeyFormModal').hidden=true}
      function openCreateAPIKey(){if(!accounts.length){toast('请先接入一个订阅账号',true);return}$('apiKeyForm').reset();editingKeyID=0;fillAPIKeyAccountOptions('');$('apiKeyEnabledField').hidden=true;$('deleteAPIKeyButton').hidden=true;$('resetAPIKeyButton').hidden=true;$('apiKeyAccount').disabled=false;$('apiKeyFormTitle').textContent='签发 API Key';$('saveAPIKeyButton').textContent='签发 Key';$('apiKeyFormModal').hidden=false;$('apiKeyName').focus()}
      function openEditAPIKey(key){$('apiKeyForm').reset();editingKeyID=key.id;fillAPIKeyAccountOptions(key.account_id);$('apiKeyAccount').value=String(key.account_id);$('apiKeyAccount').disabled=true;$('apiKeyName').value=key.name;$('apiKeyEnabled').value=key.enabled?'1':'0';$('apiKeyRpmLimit').value=key.rpm_limit||'';$('apiKeyExpiresAt').value='';$('apiKeyEnabledField').hidden=false;$('deleteAPIKeyButton').hidden=false;$('resetAPIKeyButton').hidden=false;$('apiKeyFormTitle').textContent='编辑 API Key';$('saveAPIKeyButton').textContent='保存修改';$('apiKeyFormModal').hidden=false;$('apiKeyName').focus()}
      async function saveAPIKey(event){event.preventDefault();var button=$('saveAPIKeyButton');button.disabled=true;try{var payload={name:$('apiKeyName').value.trim(),rpm_limit:$('apiKeyRpmLimit').value?Number($('apiKeyRpmLimit').value):null};if($('apiKeyExpiresAt').value)payload.expires_at=new Date($('apiKeyExpiresAt').value).toISOString();if(editingKeyID){payload.enabled=$('apiKeyEnabled').value==='1';await request('/api/api-keys/'+editingKeyID,{method:'PUT',body:JSON.stringify(payload)});closeAPIKeyForm();toast('API Key 已更新');await loadData();return}payload.account_id=Number($('apiKeyAccount').value);var result=await request('/api/api-keys',{method:'POST',body:JSON.stringify(payload)});closeAPIKeyForm();showKey(result.api_key,'API Key 已签发',result.key);await loadData()}catch(e){toast(e.message,true)}finally{button.disabled=false}}
      function ccSwitchApp(provider){return({claude:'claude',codex:'codex',grok:'grokbuild'}[provider]||'claude')}
      function ccSwitchEndpoint(provider){var origin=location.origin;if(provider==='claude')return origin+'/claude';if(provider==='codex')return origin+'/codex/v1';if(provider==='grok')return origin+'/grok/v1';return origin}
      function openCCSwitch(key,plaintext){if(!key)return;if(!plaintext){toast('没有可用的 API Key，无法导入 CC Switch',true);return}var params=new URLSearchParams({resource:'provider',app:ccSwitchApp(key.provider),name:key.name||('UniSub '+key.account_name),endpoint:ccSwitchEndpoint(key.provider),homepage:location.origin,apiKey:plaintext});window.location.href='ccswitch://v1/import?'+params.toString();toast('已唤起 CC Switch')}
      async function launchCCSwitch(key){if(!key)return;var plaintext=plaintextKeys[key.id];if(!plaintext){try{var detail=await request('/api/api-keys/'+key.id);plaintext=detail.api_key||(detail.key&&detail.key.api_key)||'';if(plaintext)plaintextKeys[key.id]=plaintext}catch(e){toast(e.message,true);return}}if(!plaintext){if(!confirm('这把 Key 签发时没有保存明文。重置后会带入 CC Switch，旧 Key 将立即失效。继续？'))return;try{var result=await request('/api/api-keys/'+key.id+'/reset',{method:'POST'});plaintext=result.api_key;if(plaintext)plaintextKeys[key.id]=plaintext;await loadData()}catch(e){toast(e.message,true);return}}openCCSwitch(key,plaintext)}
      async function keyAction(event){var button=event.target.closest('[data-key-action]');if(!button)return;var key=keys.find(function(item){return item.id===Number(button.dataset.id)});if(!key)return;if(button.dataset.keyAction==='ccswitch'){launchCCSwitch(key);return}openEditAPIKey(key)}
      async function resetEditingAPIKey(){var key=keys.find(function(item){return item.id===editingKeyID});if(!key||!confirm('确定重置 '+key.name+' ？旧 Key 将立即失效。'))return;try{var result=await request('/api/api-keys/'+key.id+'/reset',{method:'POST'});closeAPIKeyForm();showKey(result.api_key,'API Key 已重置',key);await loadData()}catch(e){toast(e.message,true)}}
      async function deleteEditingAPIKey(){var key=keys.find(function(item){return item.id===editingKeyID});if(!key||!confirm('确定删除 '+key.name+' ？使用该 Key 的请求将立即失败。'))return;try{await request('/api/api-keys/'+key.id,{method:'DELETE'});closeAPIKeyForm();toast('API Key 已删除');await loadData()}catch(e){toast(e.message,true)}}
      function roleLabel(role){return role==='admin'?'管理员':'成员'}
      function renderUsers(){if(!isAdmin()){$('userTable').innerHTML='<div class="empty">只有管理员可以管理用户。</div>';return}if(!users.length){$('userTable').innerHTML='<div class="empty">暂无用户。</div>';return}$('userTable').innerHTML='<table><thead><tr><th>用户名</th><th>角色</th><th>状态</th><th style="text-align:right">操作</th></tr></thead><tbody>'+users.map(function(u){var self=currentUser&&u.id===currentUser.id;return '<tr><td><div class="account-name">'+escapeHTML(u.username)+(self?' <span class="subtle">当前</span>':'')+'</div></td><td>'+roleLabel(u.role)+'</td><td><span class="badge '+(u.enabled?'ok':'off')+'">'+(u.enabled?'已启用':'已停用')+'</span></td><td><div class="actions"><button class="btn" type="button" data-user-action="reset-password" data-id="'+u.id+'">重置密码</button><button class="btn" type="button" data-user-action="role" data-id="'+u.id+'">'+(u.role==='admin'?'设为成员':'设为管理员')+'</button><button class="btn" type="button" data-user-action="toggle" data-id="'+u.id+'">'+(u.enabled?'停用':'启用')+'</button><button class="btn btn-danger" type="button" data-user-action="delete" data-id="'+u.id+'" '+(self?'disabled':'')+'>删除</button></div></td></tr>'}).join('')+'</tbody></table>'}
      function openUserModal(){$('userForm').reset();$('userRole').value='user';$('userModal').hidden=false;$('userName').focus()}
      function closeUserModal(){$('userModal').hidden=true}
      var resettingUserID=0;
      function openResetPasswordModal(user){if(!user)return;resettingUserID=user.id;$('resetPasswordForm').reset();$('resetPasswordUsername').textContent=user.username;$('resetPasswordModal').hidden=false;$('resetPasswordValue').focus()}
      function closeResetPasswordModal(){resettingUserID=0;$('resetPasswordModal').hidden=true}
      async function saveResetPassword(event){event.preventDefault();if(!resettingUserID)return;if($('resetPasswordValue').value!==$('resetPasswordConfirm').value){toast('两次输入的新密码不一致',true);return}try{await request('/api/users/'+resettingUserID+'/password',{method:'POST',body:JSON.stringify({password:$('resetPasswordValue').value})});closeResetPasswordModal();toast('密码已重置')}catch(e){toast(e.message,true)}}
      async function saveUser(event){event.preventDefault();try{await request('/api/users',{method:'POST',body:JSON.stringify({username:$('userName').value.trim(),password:$('userPassword').value,role:$('userRole').value})});closeUserModal();toast('用户已创建');await loadData()}catch(e){toast(e.message,true)}}
      async function userAction(event){var button=event.target.closest('[data-user-action]');if(!button||button.disabled)return;var user=users.find(function(item){return item.id===Number(button.dataset.id)});if(!user)return;var action=button.dataset.userAction;try{if(action==='reset-password'){openResetPasswordModal(user);return}if(action==='role'){await request('/api/users/'+user.id,{method:'PUT',body:JSON.stringify({role:user.role==='admin'?'user':'admin',enabled:user.enabled})});toast('角色已更新');await loadData();return}if(action==='toggle'){await request('/api/users/'+user.id,{method:'PUT',body:JSON.stringify({role:user.role,enabled:!user.enabled})});toast(user.enabled?'用户已停用':'用户已启用');await loadData();return}if(action==='delete'){if(!confirm('确定删除用户 '+user.username+' ？'))return;await request('/api/users/'+user.id,{method:'DELETE'});toast('用户已删除');await loadData()}}catch(e){toast(e.message,true)}}
      async function changePassword(event){event.preventDefault();if($('newPassword').value!==$('confirmPassword').value){toast('两次输入的新密码不一致',true);return}try{await request('/api/password',{method:'PUT',body:JSON.stringify({current_password:$('currentPassword').value,new_password:$('newPassword').value})});$('passwordForm').reset();toast('密码已更新')}catch(e){toast(e.message,true)}}
      $('loginForm').addEventListener('submit',login);$('logoutButton').addEventListener('click',logout);$('refreshButton').addEventListener('click',refreshData);$('pageAddButton').addEventListener('click',openAccountModal);$('accountForm').addEventListener('submit',saveAccount);$('accountProvider').addEventListener('change',updateCredentialHint);$('authType').addEventListener('change',updateCredentialHint);$('accountSearch').addEventListener('input',renderAccounts);$('providerFilter').addEventListener('change',renderAccounts);$('accountTable').addEventListener('click',accountAction);$('deleteAccountButton').addEventListener('click',deleteEditingAccount);$('refreshUsageButton').addEventListener('click',refreshEditingUsage);$('pageAddKeyButton').addEventListener('click',openCreateAPIKey);$('apiKeyForm').addEventListener('submit',saveAPIKey);$('keySearch').addEventListener('input',renderAPIKeys);$('keyAccountFilter').addEventListener('change',renderAPIKeys);$('keyTable').addEventListener('click',keyAction);$('deleteAPIKeyButton').addEventListener('click',deleteEditingAPIKey);$('resetAPIKeyButton').addEventListener('click',resetEditingAPIKey);$('passwordForm').addEventListener('submit',changePassword);$('pageAddUserButton').addEventListener('click',openUserModal);$('userForm').addEventListener('submit',saveUser);$('resetPasswordForm').addEventListener('submit',saveResetPassword);$('userTable').addEventListener('click',userAction);$('copyKeyButton').addEventListener('click',function(){copyText($('newAPIKey').value)});$('ccSwitchFromKeyModal').addEventListener('click',function(){openCCSwitch(pendingCCSwitchKey||keys.find(function(item){return item.id===editingKeyID}),$('newAPIKey').value)});$('logTable').addEventListener('click',logTableClick);$('logModalBody').addEventListener('click',logModalClick);$('logPager').addEventListener('click',logPagerClick);$('logAccountFilter').addEventListener('change',resetLogOffsetAndLoad);$('logProviderFilter').addEventListener('change',resetLogOffsetAndLoad);$('logStatusFilter').addEventListener('change',resetLogOffsetAndLoad);$('logSearch').addEventListener('input',function(){clearTimeout(logSearchTimer);logSearchTimer=setTimeout(resetLogOffsetAndLoad,250)});
      document.querySelectorAll('.nav button').forEach(function(el){el.addEventListener('click',function(){navigate(el.dataset.page)})});document.querySelectorAll('[data-close]').forEach(function(el){el.addEventListener('click',closeAccountModal)});document.querySelectorAll('[data-key-close]').forEach(function(el){el.addEventListener('click',function(){$('keyModal').hidden=true;$('newAPIKey').value=''})});document.querySelectorAll('[data-key-form-close]').forEach(function(el){el.addEventListener('click',closeAPIKeyForm)});document.querySelectorAll('[data-user-close]').forEach(function(el){el.addEventListener('click',closeUserModal)});document.querySelectorAll('[data-reset-password-close]').forEach(function(el){el.addEventListener('click',closeResetPasswordModal)});document.querySelectorAll('[data-log-close]').forEach(function(el){el.addEventListener('click',function(){$('logModal').hidden=true})});
      document.querySelectorAll('[data-grok-oauth-close]').forEach(function(el){el.addEventListener('click',cancelGrokOAuth)});
      if(token)showApp();
    })();
